### ISSUE TITLE
QWindowsWindow::setGeometry: Unable to set geometry

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#4186] opened 2024-11-17 03:34 UTC
I first observed this after a Windows update on my laptop.
When Leo opens all fonts are large (about 18pt)
This message appears in console log:

_QWindowsWindow::setGeometry: Unable to set geometry 2958x1518+0+53 (frame: 2980x1574-11+8) on QWidgetWindow/"LeoTabbedTopLevelClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1924x1050+0+53 (frame: 1946x1106-11+8) margins: 11, 45, 11, 11)_

Normally I see line in log:
reading settings in C:\Users\lewis\.leo\tbp_dark.leo
but this is not showing in log after the update.

Leo 6.8.3-devel, devel branch, build 959f740643
Python 3.13.0, PyQt version 6.7.3

I have confirmed only my laptop is affected.

**Comment by LewisNeal** [comment] 2024-11-17 03:57
Same issue occurs running build 9862614477, and also using default leoSettings.leo

**Comment by tbpassin** [comment] 2024-11-17 12:55
This sounds like an incompatibility between a recent Windows change and Qt. It hasn't struck me yet, thank goodness.  It seems to be about the screen resolution setting.  Qt wants to use 1050P but Windows is trying to use 1574 lines. At 1024, everything would look too large.  Maybe windows is reporting incorrect numbers when queried by Qt.

On Windows 10 there is a settings page called "Display", which I get to by typing "resolution" into the Windows-key search box.  One option offered will be "change the resolution of the display".  That will open a window that shows, among other things, "Display Resolution". See what it says. There will be a select list that shows a number of resolutions.  See if any of them match what's in the error message.

I'm sure you don't want to change the resolution setting from what you have been using but it might be worthwhile to try it temporarily to see whether it helps with this problem.

If this is a result of the recent update, a lot of people will be looking for help with it and they should be showing up online.  If the problem is wide-spread, Qt will be very interested in fixing it.

**Comment by tbpassin** [comment] 2024-11-17 13:29
> If the problem is wide-spread, Qt will be very interested in fixing it.

Or maybe not ... I found several similar reports going back years, even to Qt5.x. Some people said that setting `setMinimumSize()` on the offending components fixed that problem. Or maybe setting a size policy if it isn't already set. It definitely seems to be a Windows-only problem. The internet responses I've seen so far only talk about getting the error message, not about any actual visual effects, so perhaps this time is a little different.

**Comment by LewisNeal** [comment] 2024-11-18 09:26
Screen resolution on both my PC and laptop is 1920x1080.
I just updated to build 677f706cc and restarted Leo on laptop. The large font problem did not occur (using default leoSettings.leo).
How I wish I had just restarted Leo before doing git pull !
Earlier today running build 9862614477 I had confirmed the large font issue. So I ran git checkout 9862614477 to try and reproduce the font issue. Interestingly running the font problem does not occur.

This temporary font issue is quite annoying :) 
I'll try to reproduce the issue, but not sure I want to succeed.

**Comment by edreamleo** [comment] 2024-11-18 16:20
@LewisNeal I sometimes see a similar message. It happens infrequently.

I'll leave this issue open for now, but I suspect it is an installation issue.

**Comment by edreamleo** [comment] 2024-11-18 16:20
@LewisNeal I sometimes see a similar message. It happens infrequently.

I'll leave this issue open for now, but I suspect it is an installation issue.

**Comment by edreamleo** [comment] 2024-11-25 15:12
I am going to close this issue. Please reopen if there is something new to report.

**Closed by edreamleo** 2024-11-25 15:12 UTC
Labels: Help
