### ISSUE TITLE
VR3 erroneously complains that nbformat has not been installed

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2574] opened 2022-04-04 18:02 UTC
But I have installed it. pip list says: nbformat 5.2.0
```
Leo 6.6.1-devel, devel branch, build 235fb7110e
2022-04-04 10:19:43 -0500
Python 3.10.4, PyQt version 6.2.4
Windows 10 AMD64 (build 10.0.22000) SP0
```

**Comment by tbpassin** [comment] 2022-04-04 18:27
Looks like a line got blipped out by mistake.  Please add it back and see if the problem is resolved:

```
# nbformat (@jupyter) support, non-vital.
try:
    import nbformat
    from nbconvert.exporters import HTMLExporter
    nbformat = True         # <==== add this line
    # from traitlets.config import Config
except ImportError:
    nbformat = None
    print('VR3: *** No nbformat')
```

**Comment by edreamleo** [comment] 2022-04-05 20:32
@tbpassin Your suggested change does not work. Furthermore, setting nbformat to True would shadow the actual import. pylint should complain, and anyway shadowing an import is bad style.

**Comment by tbpassin** [comment] 2022-04-05 23:01
Ah, I forgot that was the actual name of the import and not just a flag.  Hmm, my system does not emit that message.  Just to be complete, can you successfully import nbformat from a non-Leo python session?  I assume you are using your new Python 3.10 install, is that right?

Here's what mine looks like:

```
C:\Users\tom>py -m pip show nbformat
Name: nbformat
Version: 5.3.0
Summary: The Jupyter Notebook format
Home-page: http://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.com
License: BSD
Location: c:\program files\python39\lib\site-packages
Requires: fastjsonschema, jsonschema, jupyter-core, traitlets
Required-by: ipywidgets, leo, nbclient, nbconvert, notebook
```

What is the exact message you have been getting?  There are two places in the code that might emit a message.  Do you get it when VR3 starts up, or when you try to use an @jupyter node?  I should say @jupyter nodes are working on my system, by which I mean that the notebooks are getting retrieved from their urls and are getting rendered.

Strangely enough, the same @jupyter nodes are not displaying anything in viewrendered, although I don't get any messages and I would have thought the code was still the same for VR and VR3 (I haven't checked yet to see).

**Comment by edreamleo** [comment] 2022-04-06 00:24
On Tue, Apr 5, 2022 at 6:01 PM Thomas Passin ***@***.***>
wrote:

> can you successfully import nbformat from a non-Leo python session? I
> assume you are using your new Python 3.10 install, is that right?
>

Correct. Clearly, the following import fails:

from nbconvert.exporters import HTMLExporter

I do not see the expected file, and I have not yet found a way to install
nbconvert/exporters.

Here's what mine looks like:
>
> C:\Users\tom>py -m pip show nbformat
> Name: nbformat
> Version: 5.3.0
> Summary: The Jupyter Notebook format
> Home-page: http://jupyter.org
> Author: Jupyter Development Team
> Author-email: ***@***.***
> License: BSD
> Location: c:\program files\python39\lib\site-packages
> Requires: fastjsonschema, jsonschema, jupyter-core, traitlets
> Required-by: ipywidgets, leo, nbclient, nbconvert, notebook
>
> What is the exact message you have been getting?
>
Name: nbformat
Version: 5.2.0
Summary: The Jupyter Notebook format
Home-page: http://jupyter.org
Author: Jupyter Development Team
Author-email: ***@***.***
License: BSD
Location: c:\users\edward ream\python\python310\lib\site-packages
Requires: jsonschema, jupyter-core, traitlets
Required-by: leo

> There are two places in the code that might emit a message. Do you get it
> when VR3 starts up, or when you try to use an @jupyter
> <https://github.com/jupyter> node?
>
When Leo starts up.

Edward

**Comment by tbpassin** [comment] 2022-04-06 02:16
HTMLExporter is in _Lib\site-packages\nbconvert\exporters\html.py_.  If you don't have nbconvert, that would be the cause of the problem.

I am ignorant as to whether installing nbformat also installs nbconvert or not.  Maybe not, since that pip display  doesn't say that nbformat requires it.  Aha, turns out that it's nbconvert that requires nbformat, not the other way around:

```
py -m pip show nbconvert
Name: nbconvert
Version: 6.1.0
Summary: Converting Jupyter Notebooks
Home-page: https://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.com
License: BSD
Location: c:\program files\python39\lib\site-packages
Requires: bleach, defusedxml, entrypoints, jinja2, jupyter-core, jupyterlab-pygments, mistune, nbclient, nbformat, pandocfilters, pygments, testpath, traitlets
Required-by: jupyter, notebook
```
It seems to me that we - that is, for both VR and VR3 - should make a separate import for HTMLExporter so a more appropriate message can be generated.  And wherever the requirements are listed  for installed packages, the requirement for nbformat should be changed to nbconvert.  That should automatically install nbformat.

I don't know where those installation requirements are listed.

**Comment by tbpassin** [comment] 2022-04-07 12:04
fixed in devel.

**Closed by tbpassin** 2022-04-07 12:04 UTC
Labels: Bug, Delegated
