### ISSUE TITLE
vim-open-node positions cursor at last line upon return

### ISSUE THREAD

**Issue by ktenney** [leo-editor/leo-editor#559] opened 2017-10-23 14:52 UTC
Ideally the node cursor would be at the same position as before invoking Vim, failing that, I'd prefer seeing the top of the node to seeing the bottom.

Thanks,
Kent

**Comment by edreamleo** [comment] 2017-10-24 10:01
On Mon, Oct 23, 2017 at 9:52 AM, Kent Tenney <notifications@github.com>
wrote:

> Ideally the node cursor would be at the same position as before invoking
> Vim, failing that, I'd prefer seeing the top of the node to seeing the
> bottom.
>
​Done at 2eefadc.

vim-open-node sets the cursor in vim to the selected line in Leo.
vim-open-file sets the cursor to the start of the file.

Eliminated the @bool vim_plugin_positions_cursor setting. I see no reason
to have this setting. Preserving the selected line seems natural.

Edward

**Comment by ktenney** [comment] 2017-10-25 13:50
Note: change vim to gvim, in case it matters.

vim-open-node

use case: editing an @auto node, plain text, 650 lines, line 1 in edit pane
open node in vim
make changes to file at line 300
save and quit vim, Leo informs of change asks to update node: yes

- an empty vim file remains active (with an illegal file name: <CR>,
non-existent dir ...)
- upon return to Leo line 650 is in edit pane

I'm not invested in Leo putting cursor at 300 upon return, would prefer
seeing
line 1 to seeing line 650

Thanks,
Kent

**Comment by tbnorth** [comment] 2018-04-29 03:47
Looks like the extra file is coming from
```python
cmd = self.vim_cmd + "--remote-send '<C-\\><C-N>:e " + path + "<CR>'"
```
in `leoPlugins.leo#Plugins-->External programs-->@file vim.py-->class VimCommander-->vim.open_in_vim & helpers`
According to [this](https://stackoverflow.com/questions/39858863/what-are-some-use-cases-of-e-in-vim) that should make vim re-edit the file, but it's not making it through as a command, and instead is being seen as a file name.  Switching from os.system() to subprocess.Popen() might help.

The fact that `vim-open-node` seems to work anyway probably springs from quitting vim to return to Leo, so "re-edit" is redundant.  It would be nice to have it work as intended though, without the need to quit vim.

For the cursor position in Leo on return, it seems that it's just Leo's "open changed file" mechanism picking up the change - is that what you're seeing / expecting / wanting, @ktenney?

That aside, rather than positioning the the cursor at the end of the node, it seems like it could be positioned at the first or last change in the node.  Unless vim has some sneaky way of telling you which line / column it was on when it exited, but that seems unlikely.

**Comment by ktenney** [comment] 2018-04-30 15:58
currently I'm not seeing the extra vim session, so, nevermind.

As I recall, the way to inform Leo where to locate the cursor upon
return would require vim to be in session save/restore mode, which
generates a file which includes cursor position, Leo would then
have to parse this file:
altogether too sneaky.
:-]

**Comment by edreamleo** [comment] 2018-05-01 13:40
@ktenney Thanks for the report.  I'll close this issue now.  Please reopen (or open a new issue) if problems remain.

**Comment by tbnorth** [comment] 2018-05-01 14:48
This is a two part issue, the disappearance of the extra gvim frame is only part of the request.  It's also odd because I saw the extra frame when testing.

**Closed** 2022-05-22 12:00 UTC
Labels: Enhancement, Won'tDo, Vim
