### ISSUE TITLE
Viewrendered2 Plugin Needs Way to Set Background Color for Markdown Rendering

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#815] opened 2018-03-15 15:56 UTC
The Viewrendered2 plugin display pane is unreadable when I use a dark theme and markdown rendering.  This is because the background color setting does not get applied when markdown is used.   I haven't found a way to get the md converter to set a background color.

But there is a hack.  I have found that by prefixing the md-generated html with a <style> element, the background color for the viewing pane can be changed .  Here's my added code.

In md-html(), add the following after the line html = markdown(html, mdext):

    html = '<style type="text/css">body{background-color:%s;}</style>\n' %(MD_RENDERING_BG_COLOR) + html

The code to set MD_RENDERING_BG_COLOR is added to init_config().  Add the following:

    def set_bg_color(color): global MD_RENDERING_BG_COLOR; MD_RENDERING_BG_COLOR = color
    getConfig(gc.getString, 'md-rendering-pane-background-color', 'black', set_bg_color)

This lets you set an @string setting named "md-rendering-pane-background-color" for the background color of the pane.

Finally, at the module level, say after the imports, add a declaration:

    MD_RENDERING_BG_COLOR  = ''

I suggest adding these changes into the viewrendered2 plugin.  I'm not sure if they should be applied to the current suggested changes on the development branch or whether a different change commit should be started there.

**Comment by edreamleo** [comment] 2018-03-15 16:29
On Thu, Mar 15, 2018 at 10:56 AM, tbpassin <notifications@github.com> wrote:

> The Viewrendered2 plugin display pane is unreadable when I use a dark
> theme and markdown rendering.
>
​Rev fe04fdd disables the VR2 stylesheet.  Plugins are not supposed to
dictate style-related matters.

Please let me know how this works for you.

Edward

**Comment by edreamleo** [comment] 2018-03-15 16:30
I am going to close this issue.  Please reopen if problems remain.

Note: at present VR2 is not compatible with PyQt5.

**Comment by tbpassin** [comment] 2018-03-15 17:05
I'd like to have it be re-opened.  I don't argue that the user, not the plugin, should be the one to set the style.  My proposed patch does give the users a setting to do that.

The problem I'm raising is that as it stands, there is no way to get md-rendered markup that sets any css style, whether background or something else.  If you look at the html that comes from the md converter, there is no style specification at all in the emitted html.  My hack adds a <style> element to the converter's html.  Maybe there is some way to get the converter to include style information.  I didn't find it when I took a quick look at the converter package.

I know that my proposed code looks like it has the plugin setting style colors.  But I just did that to get get some colors so that I could test each part of the code (I'd get a different color, for example, if the @string setting didn't work).  Those defaults could be removed.

Yes, I realize that VR2 isn't compatible with Qt5.  I don't know much about Qt, let alone the differences between v4 and v5.  But on 64-bit Python 2.7 on Windows, I don't know when if ever I'll be able to get a binary of PyQt5, so it's v4 for me for the present.

**Comment by edreamleo** [comment] 2018-03-15 17:41
On Thu, Mar 15, 2018 at 12:05 PM, tbpassin <notifications@github.com> wrote:

> I'd like to have it be re-opened.
>
​Done.  You don't need my permission to reopen issues.

Edward

**Comment by tbpassin** [comment] 2018-03-15 22:44
After rummaging through the viewrendered2 code some more, I see that it does pick up the setting 

   rendering-pane-background-color

and that it is available at the point of markdown conversion.  This simplifies the changes need down to two lines.  So at the location  of 

    def md_to_html(...):

add these two lines, marked diff-like with a "+":

       try:
            # Call markdown to get the string.
            mdext = c.config.getString('view-rendered-md-extensions') or 'extra'
            mdext = [x.strip() for x in mdext.split(',')]
            if pygments:
                mdext.append('codehilite')
            html = markdown(html, mdext)
         +bg_color = self.c.config.getColor('rendering-pane-background-color')
         +html = '<style type="text/css">body{background-color:%s;}</style>\n' %(bg_color) + html

**Comment by edreamleo** [comment] 2018-03-16 09:11
On Thu, Mar 15, 2018 at 5:44 PM, tbpassin <notifications@github.com> wrote:

> After rummaging through the v
​ ​
iewrendered2 code some more, I see that it does pick up the setting
​ ​
rendering-pane-background-color
​​


Right.  And the startup logic in the ViewRenderedController class sets the
background_color ivar to this color.  There is no need for the
MD_RENDERING_BG_COLOR global var
​ and related logic.​


> [Add these two lines in md_to_html]

bg_color = self.c.config.getColor('rendering-pane-background-color')
html = '<style type="text/css">body{background-color:%s;}</style>\n' %(
​    ​
bg_color) + html

Huh? The devel branch already has this code:

html = '<style type="text/css">body{background-color:%s;}</style>\n' %(
    MD_RENDERING_BG_COLOR ) + html

Rev
​​
f88865f replaces this line with:

html = '<style type="text/css">body{background-color:%s;}</style>\n' %(
    self.background_color) + html

and comments out all code relating
​​
​​
MD_RENDERING_BG_COLOR.

*​Summary​*


​Please make sure you are on the devel branch when discussing code.​


​Let me know if there are any problems with ​
​
​
f88865f.  If not, please remove the commented-out code re
​
​
MD_RENDERING_BG_COLOR.

Edward

**Comment by tbpassin** [comment] 2018-03-16 23:21
f88865f works as intended on my system.

**Comment by edreamleo** [comment] 2018-03-17 09:23
On Fri, Mar 16, 2018 at 6:21 PM, tbpassin <notifications@github.com> wrote:

> f88865f
> <https://github.com/leo-editor/leo-editor/commit/f88865f1e53f0651e08cc48c35a878d857962615>
> works as intended on my system.
>
​Thanks for this confirmation.

Edward

**Comment by edreamleo** [comment] 2018-03-17 09:42
**Note**: Creating a new comment, so that markup works.

**tbpassin**: After rummaging through the viewrendered2 code some more, I see that it does pick up the setting
​ ​rendering-pane-background-color
​​
**EKR**: Right.  And the startup logic in the ViewRenderedController class sets the background_color ivar to this color.  There is no need for the MD_RENDERING_BG_COLOR global var and related logic.​

**tbpassin**:  [Add these two lines in md_to_html]:
```python
bg_color = self.c.config.getColor('rendering-pane-background-color')
html = '<style type="text/css">body{background-color:%s;}</style>\n' %(bg_color) + html
```
**EKR**: Huh? The devel branch already has this code:
```python
html = '<style type="text/css">body{background-color:%s;}</style>\n' %(
    MD_RENDERING_BG_COLOR ) + html
```
Rev f88865f replaces this line with:
```python
html = '<style type="text/css">body{background-color:%s;}</style>\n' %(
    self.background_color) + html
```
and comments out all code relating MD_RENDERING_BG_COLOR.

*​*EKR: Summary​**

Please make sure you are on the devel branch when discussing code.​

​Let me know if there are any problems with ​ f88865f.  

**tbpassin**: f88865f works as intended on my system.
​
**EKR**: Thanks for this confirmation.

**Comment by edreamleo** [comment] 2018-03-17 09:48
Rev f88865f completes this item using a simplified version of tbpassin's initial code.

**Closed by edreamleo** 2018-03-17 09:48 UTC
