### ISSUE TITLE
Ctrl-click on a Gnx-based UNL gives errors (@language html)

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#3457] opened 2023-07-23 03:43 UTC
Ctrl-click on a Gnx-based UNL of a node which has @language directive
@language html
gives errors in Log pane:

is_sentinel: can not happen. delims: (None, '')
is_sentinel: can not happen. delims: (None, '')

**Comment by LewisNeal** [comment] 2023-07-23 04:09
For the @language directive I tested with these valid values:

actionscript, c, csharp, css, cweb, elisp, html, java, latex,
pascal, perl, perlpod, php, plsql, rapidq, rebol, shell, tcltk.

Only csharp, css, cweb, and html caused errors.

**Comment by tbpassin** [comment] 2023-07-23 11:56
I don't think it has anything to do with those specific languages.  I think there's a generic issue that when a language directive is changed, the updates to the node's data can be incomplete once in a while. See my comment in https://github.com/leo-editor/leo-editor/issues/3458.

**Comment by edreamleo** [comment] 2023-10-16 17:41
This issue is a duplicate of #3598, which contains Thomas's detailed comments.

**Closed by edreamleo** 2023-10-16 17:41 UTC
Labels: Bug
