### ISSUE TITLE
Segfault on ubuntu 16.04

### ISSUE THREAD

**Issue by kv-gits** [leo-editor/leo-editor#916] opened 2018-05-29 22:07 UTC
```
QApplication: invalid style override passed, ignoring it.

Leo 5.7.3, build 20180525162844, Fri May 25 16:28:44 CDT 2018
Git repo info: branch = master, commit = d263df9f660e
Python 3.6.5, PyQt version 5.10.1
linux
** isPython3: True
** caching enabled

[1]    14273 segmentation fault (core dumped)  python launchLeo.py
```

I read that it is PyQT issue rather than leo's one. But I could run devel leo-editor branch with no problem.
```
QApplication: invalid style override passed, ignoring it.

Leo 5.8 devel, build 20180228131330, Wed Feb 28 13:13:30 CST 2018
Not running from a git repo
Python 3.6.5, PyQt version 5.10.1
linux
** isPython3: True
** caching enabled

reading settings in /home/a1/.leo/workbook.leo
```
Ok

**Comment by kv-gits** [comment] 2018-05-30 19:51
Oh, from git repo I only could switch only to this latest version.
```
QApplication: invalid style override passed, ignoring it.

Leo 5.7.4 devel, build 20180525162844, Fri May 25 16:28:44 CDT 2018
Git repo info: branch = devel, commit = ad630465f7b7
Python 3.6.5, PyQt version 5.10.1
linux
** isPython3: True
** caching enabled

reading settings in /home/a1/.leo/workbook.leo
```
It works.

----

Leo 5.8 devel - this version I downloaded from site.

**Comment by kv-gits** [comment] 2018-05-30 20:00
I am really confused. Now all work even master branch. I made some shaman dance with apt-get and pip and that seems cause work.

**Comment by iskunk** [comment] 2018-08-09 19:31
I'm seeing this same issue on Ubuntu 18.04/Bionic, the current Ubuntu release. The lion graphic pops up for a short moment before the segfault:
```
$ python3 ./launchLeo.py 

import-jupyter-notebook requires nbformat package
setting leoID from os.getenv('USER'): 'skunk'
reading settings in /home/skunk/leo-editor/leo/config/leoSettings.leo

Leo 5.7.3, build 20180525162844, Fri May 25 16:28:44 CDT 2018
Git repo info: branch = master, commit = 3e7ba8d49c8f
Python 3.6.5, PyQt version 5.9.5
linux
** isPython3: True
** caching enabled

Segmentation fault (core dumped)
```

I ran this in GDB, and got [this voluminous backtrace](https://github.com/leo-editor/leo-editor/files/2275660/gdb.txt). Looks like something having to do with `libreadline`.

I'll be happy to provide whatever information I can, as I am currently otherwise unable to run Leo.

**Comment by iskunk** [comment] 2018-08-09 20:41
Thanks for the information @technatica. It's possible that the issue is in one of the Ubuntu Python packages, but as the error reporting isn't so great, there's no immediate way to tell.

**Comment by iskunk** [comment] 2018-08-09 20:56
Okay, I've been poring through that massive GDB backtrace, and appear to have found the problem point.

If I comment out the following line near the top of `leo/plugins/python_terminal.py`...
```
from rlcompleter import Completer
```
...then Leo starts up perfectly fine, using Ubuntu's own Python installation, and no further errors. Un-commenting the line brings the segfault back.

**Comment by edreamleo** [comment] 2018-08-17 20:44
I am going to close this issue, because there seems to be little that can be done.

Please reopen if you have ideas for avoiding the problem.

**Closed by edreamleo** 2018-08-17 20:44 UTC
Labels: Bug
