### ISSUE TITLE
'Nav Find' keyboard shortcut only works in the first 'tab'.

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3970] opened 2024-06-16 17:33 UTC
I've discovered the very cool 'CTRL+SHIFT+F' keyboard shortcut that places focus in the 'nav pane' search field, as opposed to the regular 'CTRL+F' which places focus in the regular 'find-pane' search field. (_I'll add it to LeoInteg and LeoJS too! As a sidenote, this mimics the vscode ctrl+f and Ctrl+shift+f which are also respectively a regular search and a 'super' search, so it's kind of nice that this exists and has coincidentally the same keyboard shortcut! )_

But, problem is, this cool feature only seems to work in the first opened tab of Leo! 

To reproduce: Open a Leo file, observe the effect of CTRL+SHIT+F which makes the **nav pane** visible and places the cursor in its search input field. Now create a new file (CTRL+N) and try to use the CTRL+SHIT+F  shortcut... A single capital 'F' is placed in the body pane instead... Go back to the first original tab and observe that it works again.. (only on the first original tab)

**Comment by tbpassin** [comment] 2024-06-18 11:40
I didn't even know about this feature, and I use the Nav tab all the time!  I reproduced your result but there's another case you didn't describe.  That is whether the shortcut works in already-open outlines when more than one are open.

In my system, CTRL-SHIFT-F works as expected for all open outlines, not just the first one. It failed in a new outline, and here's some more information:

1. The shortcut continues to fail after I have typed text into the node;  On my system it deposits an unknown character symbol, not an "F". 
2.  The shortcut still fails after I have saved the new outline;
3. The shortcut succeeds after I close and reload the new outline.

This last suggests to me that there is a deeper problem to be addressed - why should a new outline that has been saved with a new name act differently than after it has been closed and reopened?  And what else isn't working right for new outlines?

**Comment by edreamleo** [comment] 2024-06-18 12:55
@tbpassin Thanks for your testing. Some comments:

- The plugin doesn't have an event handler for `new` events. That will be easy to fix.
- The `new` command can't generate, say, an `after-create-leo-frame` event,
  because (big sigh) the new event might break existing plugins!  Indeed, `quicksearch.py` might break!
- Weird: the plugin honors `Ctrl-g` but not `Alt-x'.

**Comment by edreamleo** [comment] 2024-06-23 18:00
@boltex Closed via PR #3976. The fix is a pure hack, but I can see no other way to add the `Ctrl-Shift-f` binding without making significant changes to Leo's general key-handling code and I have no desire to do so.

Happily, Leo's key-handling mess has no effect on LeoJS!

**Closed by edreamleo** 2024-06-23 18:00 UTC
Labels: Bug

**Comment by boltex** [comment] 2024-06-23 18:43
@edreamleo Thanks, yes indeed the key bindings-to-commands in LeoJS have no similarities at all to the way it works in Leo.
