### ISSUE TITLE
Looks like it's possible for an int value to throw off headstring creation via s.replace()?

### ISSUE THREAD

**Issue by tscv11** [leo-editor/leo-editor#811] opened 2018-03-15 04:46 UTC
Internal Leo error in setHeadString
789
Called from run, load, runMainLoop, eventFilter, masterKeyHandler, doMode, callStateFunction, fullCommand, callAltXFunction, executeAnyCommand, sqlite_import_table, __init__, initUI, pick_action, grand_central, import_table4, __set_h, setHeadString, initHeadString
Please report this error to Leo's developers
Traceback (most recent call last):

File "/home/tsc/Desktop/leo-editor/leo/core/leoNodes.py", line 2561, in setHeadString
v._headString = s.replace('\n','')

AttributeError: 'int' object has no attribute 'replace'

I will try to work on this soon, but I can't promise because a lot of big errors have been cropping up in leo4sqlite that I feel compelled to attack :)

tscv11

**Comment by edreamleo** [comment] 2018-03-15 07:40
On Wed, Mar 14, 2018 at 11:46 PM, tscv11 <notifications@github.com> wrote:

> Internal Leo error in setHeadString
> 789
> Called from run, load, runMainLoop, eventFilter, masterKeyHandler, doMode,
> callStateFunction, fullCommand, callAltXFunction, executeAnyCommand,
> sqlite_import_table, *init*, initUI, pick_action, grand_central,
> import_table4, __set_h, setHeadString, initHeadString
> Please report this error to Leo's developers
> Traceback (most recent call last):
>
> File "/home/tsc/Desktop/leo-editor/leo/core/leoNodes.py", line 2561, in
> setHeadString
> v._headString = s.replace('\n','')
>
> AttributeError: 'int' object has no attribute 'replace'
>
​Presumably the real error is in import_table4 ;-)

Edward​

**Comment by tbnorth** [comment] 2018-03-15 13:21
On Thu, 15 Mar 2018 04:46:40 +0000 (UTC)
tscv11 <notifications@github.com> wrote:

> Internal Leo error in setHeadString
> 789
> Called from run, load, runMainLoop, eventFilter, masterKeyHandler,
> doMode, callStateFunction, fullCommand, callAltXFunction,
> executeAnyCommand, sqlite_import_table, __init__, initUI,
> pick_action, grand_central, import_table4, __set_h, setHeadString,
> initHeadString Please report this error to Leo's developers Traceback
> (most recent call last):
> 
> File "/home/tsc/Desktop/leo-editor/leo/core/leoNodes.py", line 2561,
> in setHeadString v._headString = s.replace('\n','')
> 
> AttributeError: 'int' object has no attribute 'replace'

This can be caused by 

  p.h = 2

instead of

  p.h = str(2)

not sure if that's the situation the "Please report this error to Leo's
developers" was aimed at, or if the message is there because assigning
to p.h is not expected to fail with valid inputs.

Cheers -Terry

> I will try to work on this soon, but I can't promise because a lot of
> big errors have been cropping up in leo4sqlite that I feel compelled
> to attack :)
> 
> tscv11
>

**Comment by edreamleo** [comment] 2018-03-15 13:54
On Thu, Mar 15, 2018 at 8:21 AM, Terry Brown <notifications@github.com>
wrote:
​
​

> AttributeError: 'int' object has no attribute 'replace'
>
> This can be caused by
>
> p.h = 2
>
> instead of
>
> p.h = str(2)
>

​My point exactly.​



> not sure if that's the situation the "Please report this error to Leo's
> developers" was aimed at, or if the message is there because assigning
> to p.h is not expected to fail with valid inputs.
>

​The question is moot if we regard plugin devs as Leo devs ;-)

However, it would probably be smoother to attempt a conversion to int in
the __h setter.

Hmm. v.​
​setHeadString​

​does attempt some recovery.  It could silently put repr(s) into the
headline, assuming it fits on a single line.​ But all things considered, I
think the present code is best. It alerts the dev, of whatever kind, that
something is not as expected.

Edward

**Comment by edreamleo** [comment] 2018-03-15 13:55
I am going to close this issue. Imo v.setHeadString issues helpful warnings, and issues them appropriately.  I don't believe it is wise to ignore unexpected inputs to fundamentally important methods.

**Closed by edreamleo** 2018-03-15 13:55 UTC
Labels: Bug

**Comment by tscv11** [comment] 2018-03-15 16:07
Very interesting, thank you both! That _was_ the problem: I just switched to str(2) instead of 2 as Terry said (although I did it on my own before reading this page ; )  Leo4sqlite keeps track of the column's data type affinities (for exports) so it doesn't matter if it's a string internally.
