### ISSUE TITLE
Status Bar Won't Accept Style

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#1218] opened 2019-06-19 23:01 UTC
The status bar won't accept styling.

QLineEdit#status1 and QLineEdit#status2 simply refuse to be styled for background color, font color, border etc. They will not inherit from QWidget. They appear grayish with a blackish text colour in all themes that are included with Leo.

Gammaray reports that both status1 and status2 are the right names for the visible widgets and that they are both QLineEdit widgets so I am sure they have been addressed correctly.

A cursory examination of the code at `/home/chris/leo-editor/leo/core/LeoPyRef.leo#Code-->Qt gui-->@file ../plugins/qt_frame.py-->class LeoQtFrame (leoFrame)-->qtFrame.class QtStatusLineClass-->QtStatusLineClass.ctor` yields nothing glaring to me.

**Comment by technatica** [comment] 2019-06-19 23:27
Neither object will inherit from the universal style.

```

* {
  background: @dark-base 3;
}
```

**Comment by edreamleo** [comment] 2019-06-20 02:20
On Wed, Jun 19, 2019 at 6:01 PM Chris George <notifications@github.com>
wrote:

> The status bar won't accept styling.
>
It works for me.

Remember that Qt stylesheets are way too fragile. Any stylesheet error
ruins later rules.

Edward

**Comment by technatica** [comment] 2019-06-20 03:17
Good point.

But I tried to style it using every single one of the themes that ship with Leo before filing the bug.

And this afternoon I reinstalled Leo completely from scratch before I got started.

**Comment by technatica** [comment] 2019-06-20 03:30
The universal style should apply to ALL objects that do not have a specific style and it doesn't apply to them.

I have been through all the other widgets and they all respond correctly.

**Comment by edreamleo** [comment] 2019-06-20 13:05
On Wed, Jun 19, 2019 at 10:30 PM Chris George <notifications@github.com>
wrote:

> The universal style should apply to ALL objects that do not have a
> specific style and it doesn't apply to them.
>
> I have been through all the other widgets and they all respond correctly.
>
I've assigned this for 6.0.  I'll see what I can discover, but no promises.

Edward

**Comment by technatica** [comment] 2019-06-20 13:33
I will keep looking, starting with a peek at what the code looked like back
before it was changed from the old style in response to that open Qt bug.

Chris

**Comment by edreamleo** [comment] 2019-06-20 13:47
On Thu, Jun 20, 2019 at 8:33 AM Chris George <notifications@github.com>
wrote:

> I will keep looking, starting with a peek at what the code looked like back
> before it was changed from the old style in response to that open Qt bug.
>

Good idea.

Edward

**Comment by technatica** [comment] 2019-06-20 15:42
Code changes on January 7, 2019 broke this.

Rev. 23643d4 works.
Rev. d2180d5 doesn't.

And it is way above my paygrade to try to tell you why. That commit is rather thick.

**Comment by edreamleo** [comment] 2019-06-20 16:11
On Thu, Jun 20, 2019 at 10:42 AM Chris George <notifications@github.com>
wrote:

> Code changes on January 7, 2019 broke this.
>
> Rev. 23643d4
> <https://github.com/leo-editor/leo-editor/commit/23643d40efca69ef6639935ed7b4f996c61dbde5>
> works.
> Rev. d2180d5
> <https://github.com/leo-editor/leo-editor/commit/d2180d56261751af3d3e1f5fdc64f569294a8bb2>
> doesn't.
>

Thanks for these researches.  I'll investigate.

Edward

**Comment by technatica** [comment] 2019-06-21 20:37
The following is a screen cap of a Gammaray view of Leo's object tree.

Note the three MainWindow objects.

All of their trees are identical. Interrogating objects only expands the first MainWindow tree.

More reading is required.

![Screenshot_20190621_133209](https://user-images.githubusercontent.com/5809169/59949930-6a547280-9429-11e9-9d48-595dc6bb2099.png)


Do you have a convention when it comes to naming objects? Some have no name, just an address. I was wondering if the fact they have no name has an impact on inheritance. Both status1 and status2 are part of a tree with a parent that has no name.

**Comment by edreamleo** [comment] 2019-06-21 20:50
Because there is a merge involved, we have to look earlier. Likely the problem (changed behavior) is with:
```
rev e2da492f79, January 6, 2019 at 14:19:22. 
Simplified QtStatusLineClass.put_helper to avoid using ~= completely.
```

The relevant code:

```python

def put_helper(self, s, w, bg=None, fg=None):
    '''Put string s in the indicated widget, with proper colors.'''
    c = self.c
    bg = bg or c.config.getColor('status-bg') or 'white'
    fg = fg or c.config.getColor('status-fg') or 'black'
    if True:
        # Work around #804. w is a QLineEdit.
        w.setStyleSheet('background: %s; color: %s;' % (bg, fg))
    ...
```

**Comment by edreamleo** [comment] 2019-06-21 20:56
I have just confirmed that `@color status-bg =red` works.

My apologies for the great confusion.  

All style sheets should be changed. I'll comment out the non-functional 'background' properties, with a reference to the settings.

**Comment by edreamleo** [comment] 2019-06-21 21:21
Rev aa7649 fixes both Breeze Dark themes.  BTW, they look great.

**Comment by edreamleo** [comment] 2019-06-21 21:35
Rev 7bb0ce5 in devel completes work on this issue.  All standard theme files warn that `@color status-bg' overrides the background properties in QLineEdit#status1, QLineEdit#status2 selectors.

**Closed by edreamleo** 2019-06-21 21:35 UTC
Labels: Help

**Comment by technatica** [comment] 2019-06-21 21:38
Heh, I just arrived in the same place.

Adjustments coming soon.

**Comment by edreamleo** [comment] 2019-06-21 22:49
On Fri, Jun 21, 2019 at 4:38 PM Chris George <notifications@github.com>
wrote:

> Heh, I just arrived in the same place.
>
> Adjustments coming soon.
>

Thanks for all the work you are doing with Themes.

Edward
