### ISSUE TITLE
Using Ctrl-F crashes leo

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#865] opened 2018-04-20 00:59 UTC
Ctrl-f correctly highlights the Find Tab, but if any key is pressed, leo hard crashes with
[Python has stopped working].

Traceback (most recent call last):
  File "N:\git\leo-editor\leo\plugins\qt_frame.py", line 813, in wrapper
    return self.keyPress(event)
  File "N:\git\leo-editor\leo\plugins\qt_frame.py", line 848, in keyPress
    stroke = ef.toStroke(tkKey, ch) # ch not used.
TypeError: toStroke() takes 2 positional arguments but 3 were given

N:\git\leo-editor>

Leo Log Window
Leo 5.7.2 devel, build 20180419082201, Thu Apr 19 08:22:01 CDT 2018
Git repo info: branch = devel, commit = 051da573cd5b
Python 3.6.5, PyQt version 5.10.1
Windows 10 AMD64 (build 10.0.16299) SP0
isPython3: True
caching enabled

**Comment by edreamleo** [comment] 2018-04-20 12:00
Fixed in devel at 077587438.

A strange bug, and a bit concerning to me.  Apparently I made a change in devel that was intended for the "keys2" branch.

**Closed by edreamleo** 2018-04-20 12:00 UTC
