### ISSUE TITLE
some commands can not exec in dev 56b83585bd1f

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#870] opened 2018-04-23 12:40 UTC
in body pane: Ctrl + Shift + 0  can not comment code now
in body pane: Shift + : can not exec vim command
in log pane: Ctrl + Home can not go to 1st line

***

Leo Log Window
Leo 5.7.2 devel, build 20180419082201, Thu Apr 19 08:22:01 CDT 2018
Git repo info: branch = dev, commit = 56b83585bd1f
Python 2.7.12, PyQt version 4.8.7
linux2
isPython3: False
caching enabled
redefining abbreviation ,, 
from u"{|{x='__NEXT_PLACEHOLDER'}|}" to u'__NEXT_PLACEHOLDER'
reading: /home/swot/pyenv/xservice36/code/XService.leo
read 89 files in 1.16 seconds
read outline in 1.47 seconds

**Comment by edreamleo** [comment] 2018-04-23 14:38
On Mon, Apr 23, 2018 at 7:40 AM, wangzhaohe <notifications@github.com>
wrote:

> in body pane: Ctrl + Shift + 0 can not comment code now
>
​The default binding has changed in leoSettings.leo.​

Does it work if you define the settings in myLeoSettings.leo?

in body pane: Shift + : can not exec vim command
>
To what command is Shift+ bound?​


> in log pane: Ctrl + Home can not go to 1st line
>
​This works for me.  Please run Leo from a console, add the following line
to k.masterKeyHandler, and report what happens.

    g.trace(repr(event.char), event.stroke)

Edward

**Comment by edreamleo** [comment] 2018-04-23 16:25
The cause of the problem with Shift+ is the following:
```
master: shift+: masterKeyHandler <KeyStroke: 'plus'> '+'
devel:  shift+: masterKeyHandler <KeyStroke: '+'> '+'
```
The fix will be to replace 'plus' by '+' in the vim code, probably in vc.create_motion_dispatch_d.

**Comment by edreamleo** [comment] 2018-04-24 12:10
On Mon, Apr 23, 2018 at 9:38 AM, Edward K. Ream <edreamleo@gmail.com> wrote:

​Please report the new vim traces when attempting to do what you want to do.

Edward

**Comment by edreamleo** [comment] 2018-04-26 11:01
@wangzhaohe I am going to close this issue, based on your comments.

Please reopen (or open a new issue) if any key-handling problems remain.

**Closed by edreamleo** 2018-04-26 11:01 UTC
Labels: Bug
