### ISSUE TITLE
Menu key (between alt and ctrl key) writes 'menu'

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#918] opened 2018-05-30 02:28 UTC
With cursor focus in body pane, press the Menu key (between alt and ctrl key). This writes text 'menu' in the pane.
Maybe a bug?

**Comment by edreamleo** [comment] 2018-05-30 07:27
This is essentially a duplicate of #917. I'll append your report to that issue.

**Closed by edreamleo** 2018-05-30 07:27 UTC
Labels: Duplicate

**Comment by LewisNeal** [comment] 2018-05-30 23:12
Also refer #901
