### ISSUE TITLE
underindent-escape-string

### ISSUE THREAD

**Issue by veksha** [leo-editor/leo-editor#2702] opened 2022-07-03 01:51 UTC
Hi, on python file @clean import with comments that are underindented importer creates wrong tree outline and not inserts underindent-escape-string at all.
How can I enable this functionality?
Thanks.

**Comment by tbpassin** [comment] 2022-07-03 12:31
As a workaround, if the files import correctly into @file nodes, you can do that and then change the headline to @clean.  Next time you save, these files will be @clean.

**Comment by veksha** [comment] 2022-07-03 13:56
thanks for reply.
changed to @file, cleaned all, selected "refresh from disk" -> but nothing happens.

**Comment by tbpassin** [comment] 2022-07-03 14:15
I wasn't thinking completely clearly about my assumptions when I wrote my suggestion.  Could you try importing the file using the File/Import Files/ Import Any File menu item?  It should import as an @auto file.  If this import seems correct, then you can change its headline to an @clean node and re-save.

If importing like this does not import correctly either, than there may be no work-around.

Can you attach a file that shows this problem - or preferably, a simplified short version?  That would help track down the cause.  Also explain in what ways the imported file is incorrect, if you would.

**Comment by veksha** [comment] 2022-07-03 14:38
I have tried "Import Any File" menu item already. @auto acts the same, unfortunately.

basically my project uses comments that have no indent at all. that is the problem for Leo.
It thinks that this is a new node and it stops adding subnodes. (so tree structure will not contain all procedures (def) as subnodes.)
[py_import_test.zip](https://github.com/leo-editor/leo-editor/files/9034960/py_import_test.zip)

I expect that Leo will ignore commented lines' indentation and all "def"-s of a Class will be populated as sub-nodes.
Also I expect that Leo will insert underindent-escape-string, so when i save the file it would have no diff-s with prior version.

**Comment by tbpassin** [comment] 2022-07-03 16:02
Yes, I see the problem.  Too bad the work-around doesn't work. I am not familiar with any of the import code so I have nothing quick and easy to offer.

I did try one thing, though.  I created a new node, and pasted all the text from your file into it.  I gave it an @clean headline and saved the outline.  When I closed and reopened the outline, the entire file was there, unindented comments and all.  Next I put the first part of the MemoScreen class into an @other node, including the `def render() ` part (that has an unidented comment), and that also works correctly.

So it seems that if you want to paste the file contents into a node, and then structure the file yourself, the resulting structured file tree will be maintained.  This is not ideal, but it would give you a way to get files like this into Leo pending correction of the problem.

**Comment by veksha** [comment] 2022-07-03 16:44
@tbpassin, do you mean that I need to include "class" line in the node, so the indentation will match to unindented comment?

![image](https://user-images.githubusercontent.com/275333/177049162-0e95c784-085b-456d-8ca6-94050403d22e.png)

**Comment by tbpassin** [comment] 2022-07-03 17:14
No, I don't think so.  I just made an arbitrary choice of where to make a division, such that the unindented comment would be in the "@others" part.  I thought that would be a reasonable way to test whether the file tree would reconstruct properly when the outline was re-opened.

But I just noticed that to be able to keep the comment block un-indented , the "@others" directive may also need to be un-indented (depending on where it is located), which works but is not how it's usually done.  For example:

```
class MemoScreen(HistoryScreen):
    def __init__(self, memo, columns, lines, h_dlg, colored=0):
        self.memo = memo
        self.h_dlg = h_dlg
        self.no_ro = partial(self.memo.set_prop, PROP_RO, False)
        self.ro = partial(self.memo.set_prop, PROP_RO, True)

        self.top = 1
        self.colored = colored

        super(MemoScreen, self).__init__(columns, lines, sys.maxsize)

@others

    def pop_history_line(self):
        chars = self.history.top.popleft()
        text = ''.join( (chars[char].data for char in range(self.columns)) )
        return chars, text
```
 In the `@others` node:

```
    def render(self,line):
#        is_wide_char = False
#        s = ''
#        line = self.buffer[line]
#        for x in range(self.columns):
#            if is_wide_char:  # Skip stub
#                is_wide_char = False
#                continue
#            char = line[x].data
#            assert sum(map(wcwidth, char[1:])) == 0
#            is_wide_char = wcwidth(char[0]) == 2
#            s += char
#        return s

        # TODO: test with wide chars
        s = ''.join( (self.buffer[line][char].data for char in range(self.columns)) )
        return s
```

**Comment by veksha** [comment] 2022-07-03 21:21
the file tree can't be reconstructed in an automatic way for me, unless i delete all subnodes and clear all text out of the body.
only then i can use "refresh from disk" and it starting to construct a tree. wrong tree of course.

**Comment by edreamleo** [comment] 2022-08-16 19:05
I am going to close this issue. Leo no longer supports underindented strings.

**Closed by edreamleo** 2022-08-16 19:05 UTC
Labels: Bug
