### ISSUE TITLE
Can't Save File with "..\" in @path directive

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#1907] opened 2021-04-25 04:09 UTC
Somewhere in the very recent past, I found that I can't save a plugin file that has "..\plugins" in the path.  Specifically, I have this construct (these paths are for testing, but my real plugin file isn't saving either:

```
-@path d:\temp\plugins
    -@file ..\plugins\plugin1.py
```

Note that this is on Windows. When I make a change to the file and try to save, I get a message that the file can't be saved because of errors. The directory _d:\temp\plugins_ gets created, but not the file.  I have tried with forward slashes as well with the same result.

One time the file did get created, but then it couldn't be changed.  Except ... erratically changes could be saved.

@files without the "..\" construct save normally.  Also, an @clean ../plugin/xxx file did not get created, but after I created it outside of Leo, changes did get saved **sometimes**.  _Refresh From Disk_ always works so far, so presumably Leo is constructing the path correctly.

I saw error messages like these:
```
initWriteIvars Did not create ../plugins for ../plugins/testplugin.py
```
I'm wondering if there isn't some kind of locking problem.  Maybe after reading an external file, Leo isn't giving up a lock somehow.

Version info:
```
Leo 6.4-devel, devel branch, build 3282f33cee
2021-04-22 15:25:27 -0500
Python 3.8.9, PyQt version 5.15.1
Windows 10 AMD64 (build 10.0.19041) SP0
```
The changeset is this evening's pull.

**Comment by tbpassin** [comment] 2021-05-18 14:15
I have a fix for this problem.  But I don't know if it will cause problems for some other edge cases.  The problem occurs in atfile.py, starting around line 208.  _g.makeAllNonExistentDirectories()_ gets called twice, the second time with a path expression that doesn't create new directories, and finally an incorrect path is constructed.

To recap the issue, Leo won't save my @file files when they have this path structure:

```
@path <absolute path>\plugins
      @file ..\plugins\<filename>
```
Leo's code base uses this path setup in many places.

In _atfile.py_, around line 208, we use two variables, _defaultDirectory_ and _targetFileName_.  Apparently either one can be missing (presumably None or an empty string).  The logic for handling these cases is a little messed up.  In pseudo code, with my comments:
```
if defaultDirectory:  # presumably might be None
    c.expand_path_expression(defaultDirectory)
    # make all directories in this path as needed

targetFileName = c.expand_path_expression(targetFileName)
# If targetFileName contained "..\", it still contains it
# after the expansion.  That's a problem
if targetFileName:  # presumably might be None
    theDir = g.os_path_dirname(targetFileName)
    # make all directories in this path as needed
    # ...
return g.os_path_realpath(
            g.os_path_finalize_join(defaultDirectory, targetFileName))
# This returned path still contains "..\", and that causes the failure of Leo to write the file.
```    

In addition, what should happen if _targetFileName_ was None? The code doesn't handle this case.  I don't know if that can ever happen, but if not, then we don't need the `if targetFileName` line.

[Continued in the following comment]

**Comment by tbpassin** [comment] 2021-05-18 14:40
I have a working fix that allows me to save my "..\" files, but I don't know if it handles all the other possibilities because I don't know what else can arise.  I assume that targetFileName is the value of the @file headline after the @file directive, "..\" and all.  I assume that the defaultDirectory is the result of all the @path expressions, or the outline's path if there are no @path nodes.

``g.os_path_realpath(
                                   g.os_path_finalize_join(defaultDirectory, targetFileName))`` does the right thing when the targetFileName includes"..\".  But the attempt to make missing directories fails when the path contains "..\".  This is the source of the problem.

There are a number of ways to fix this, but they need to handle all the possible cases, and I'm not sure what they all are.  Here are the ones I know about;

1. defaultDirectory is None or '';
2. targetFileName is None or '';
3. defaultDirectory contains one or more steps with "..\";
4. targetFileName contains "..\";
5. targetFileName contains "~";
6. defaultDirectory contains "~"

Are there any other possibilities?

**Comment by edreamleo** [comment] 2021-05-18 18:05
@tbpassin This issue was not on my radar because it did not have a milestone. Now it does. I'll get to it in the next day or two.

**Comment by tbpassin** [comment] 2021-05-19 14:38
Here is the changed code I've been using.  As I said, I don't know if there are edge cases where it won't work.  Starting around line 206 in atfile.py, replace exiting code with this:

```    # Return the finalized file name.
    # #1341 and #1450.
    make_dirs = c and c.config and c.config.create_nonexistent_directories
    target = targetFileName or ''
    targetFileName = c.expand_path_expression(targetFileName)

    if defaultDirectory:
        defaultDirectory = c.expand_path_expression(defaultDirectory)
        fullpath = g.os_path_realpath(
                            g.os_path_finalize_join(defaultDirectory, target))
        fulldir = g.os_path_dirname(fullpath)
        if make_dirs:
            ok = g.makeAllNonExistentDirectories(fulldir)
            if ok:
                return fullpath
            else:
                g.error(f"Did not create default directory: {defaultDirectory}")
                return None

    # #1341 and #1450.
    if targetFileName:
        theDir = g.os_path_dirname(targetFileName)
        if theDir and make_dirs:
            ok = g.makeAllNonExistentDirectories(theDir)
            if not ok:
                g.trace(f"Did not create {theDir} for {targetFileName}")
                return None
        # #1341.
        return g.os_path_realpath(
            g.os_path_finalize_join(theDir, targetFileName))
    return None
```

**Comment by edreamleo** [comment] 2021-05-20 12:58
@tbpassin At present, this is the only remaining bug scheduled for Leo 6.4. Imo, it is a release blocker. It's next on the list.

**Comment by edreamleo** [comment] 2021-05-20 13:08
@tbpassin I don't want to add a special case (g.os_path_realpath) to the atFile code. Instead, I would prefer to base any fix on g.fullPath.  We'll see if that is possible.

**Comment by tbpassin** [comment] 2021-05-20 14:04
In my example code above, `g.os_path_realpath` isn't really a special case.  The old code returns `g.os_path_realpath()` anyway.  My code just returns it sooner if we don't need the `if targetFileName` branch.  and I thought that the result of the operation would be a more reliable input to `g.makeAllNonExistentDirectories()` than what the old code has.

The old code calls `g.makeAllNonExistentDirectories()` *twice*, which is not necessary when there is a *defaultDirectory*  if you put the pieces together the way I did.

I find it hard to know the differences between several of those methods, like `g.os_path_realpath()`  vs `g.fullPath()`, so I'm always groping in the dark about which one to use when.

**Comment by edreamleo** [comment] 2021-05-21 15:21
@tbpassin Thanks, Tom, for your comments.

I agree that no code should call g.makeAllNonExistentDirectories twice.

"I find it hard to know the differences between several of those methods, like g.os_path_realpath() vs g.fullPath(), so I'm always groping in the dark about which one to use when."

Imo, g.fullPath should "just work" in all (almost all?) situations. This will be one of my goals in dealing with #1907.

**Comment by edreamleo** [comment] 2021-05-26 13:57
@tbpassin I'm beginning to come up to speed on this issue. I have deleted one earlier comment because it was ill informed.

**Comment by edreamleo** [comment] 2021-05-26 17:29
@tbpassin Everything seems to be working pretty much as I expect.

Some comments:

- I assume that `@bool create-nonexistent-directories = True` is in effect.
- For leo itself, the following both work for me:
```
  @file ../plugins/backslash_test.py
  @file ..\plugins\backslash_test.py
```
Yes, the issue is about creating non-existent directories, but for Leo the directory *does* exist, so I don't understand how you noticed a change.

**Comment by edreamleo** [comment] 2021-05-26 17:36
I am inclined to close this issue. However, I'll leave it open awhile longer while I await further comments.

**Comment by tbpassin** [comment] 2021-05-26 19:31
Yes, please do keep it open.  I have had the same problem in both Windows and Linux, so it's not just some quirk of one Leo setup and configuration.

I agree that the issue is limited to _at.initWriteIvars_. But although you write that you are "not convinced it is buggy", I think it is, in at least one place:

Starting a about line 217, we have 
~~~
        targetFileName = c.expand_path_expression(targetFileName)
        if targetFileName:
            theDir = g.os_path_dirname(targetFileName)
            if theDir and make_dirs:
                ok = g.makeAllNonExistentDirectories(theDir)
                if not ok:
                    g.trace(f"Did not create {theDir} for {targetFileName}")
                    return None
~~~
The problem here is not having a second call to _g.makeAllNonExistentDirectories()_.  The problem is calling it with "..\\" in the expression for _theDir_.  This causes the call to fail, and then the method fails, which causes the file not to be written.  I know that _theDir_ contains "..\\" because I put a print statement there and saw it.

**Comment by edreamleo** [comment] 2021-05-27 11:03
@tbpassin PR #1908 contains a new approach. Please test the ekr-backslash branch and report your experiences.

This could be called a "risky" change, but I think it cuts through a lot of unnecessary complications. We'll see.

I still urgently want to know how to reproduce this issue. Please send me an example .leo file that illustrates the problem (on Windows). Please use the following directory structure:
```
@path c:\test\backslash_dir
      @file ..\backslash_dir\backslash_test.py
```
Thanks.

**Comment by tbpassin** [comment] 2021-05-27 12:26
This fails on Windows using this morning's devel branch:
~~~
<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<vnodes>
<v t="tom.20210527075447.2"><vh>@path c:\test\leo\backslash_dir</vh>
<v t="tom.20210527075514.1"><vh>@file ..\backslash_dir\backslash_test.py</vh></v>
</v>
</vnodes>
<tnodes>
<t tx="tom.20210527075447.2"></t>
<t tx="tom.20210527075514.1">xxxx
</t>
</tnodes>
</leo_file>
~~~
I couldn't attach the Leo outline because I couldn't save it!  The results were that the new `backslash_dir` directory was created but the new file was not, just as you would expect from the atfile code.

It occurs to me that perhaps the directory that Leo is started from might make a difference.   In this case, I launched Leo from a console whose current directory was the equivalent of "~".  I just tried starting Leo from the c:\test directory, and now the file can be saved.

I also tried it starting Leo from c:\temp.  The file got created.  It may only be failing when Leo is started from the "~" directory.  That was _C:\Users\tom_ in this case.

So that's the difference - the starting directory.  **Finally** something that can be tested!

It also occurs to me to wonder if there might be similar code for other atxxx type to clean up, such as @clean.

**Comment by tbpassin** [comment] 2021-05-27 12:36
I just tested your new code from 919fb5e, and it worked for all three starting directories. (I haven't actually looked at the new code yet.  That will be next).

BTW, in case anyone doesn't realize it, in Windows the equivalent of "~" is `%USERPROFILE%`.

**Closed** 2021-05-27 21:39 UTC
Labels: Bug
