### ISSUE TITLE
simulateCommand: no command for <command-defined-by-plugin>

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#560] opened 2017-10-24 02:25 UTC
---------------
Background
---------------
A short time ago, EKR decided that plugins should not define any shortcuts.  Consequently, EKR recommended that plugins limit themselves to defining commands.  This allows users to define shortcuts that use the commands defined by plugins.  For example:
```
Headline:
    @command babel-exec @key=Shift-Ctrl-B

Body:
    c.k.simulateCommand('babel-exec-p')
```
For the relevant discussions see:
```
https://groups.google.com/forum/?fromgroups#!searchin/leo-editor/plugin$20shortcut%7Csort:date/leo-editor/ELGwNEmZ2Ho/o87K4BrzAQAJ

https://groups.google.com/forum/?fromgroups#!searchin/leo-editor/plugin$20shortcut%7Csort:date/leo-editor/EfWG0-GjADw/TIXh80quAAAJ
```
----------------
The Problem
----------------
This no longer works.  The command defined by the plugin (for example babel-exec-p) is in the list of commands displayed by print-commands.  But c.k.simulateCommand() displays the error message:
```
simulateCommand: no command for babel-exec-p
```
-------------------------
Commit Information
-------------------------
The change occurred after:

```
Leo 5.5, build 20170816073453, Wed Aug 16 07:34:53 UTC 2017
Git repo info: branch = master, commit = 546047bfd20e
 ```

And before:
```
Leo 5.6, build 20171020132815, Fri, Oct 20, 2017  1:28:15 PM
Git repo info: branch = master, commit = e996713191de
```
-------------------
Bisect Problem
-------------------
I wrote a minimal plugin to test a commit and I tried to use git bisect to find where the change occurred, but to my surprise this was not possible:
```
2017-10-23 18:50:45 /pri/git/leo-editor
$ git bisect start 546047bfd20ecb55f8f2047a8a69d47ec269cc18 e996713191de88647fe03832c04a9b926abe6ec1
Some good revs are not ancestor of the bad rev.
git bisect cannot work properly in this case.
Maybe you mistook good and bad revs?
2017-10-23 18:50:48 /pri/git/leo-editor
```
--------------
Test Plugin
--------------
The source is in gist:
```
https://gist.github.com/SegundoBob/49c421b2b28b17ff72b1507775a8c640
```
Put these files in one directory.  Put an empty __init__.py in this directory.  Put a link to file helloWorld.py in your Leo-Editor plugin directory.  For example:
```
2017-10-22 15:54:50 /pri/git/leo-editor/leo/plugins
$ ln -s '/pri/git/leo_bug_demos/pluginCmd/helloWorld.py' helloWorld.py
2017-10-22 15:56:01 /pri/git/leo-editor/leo/plugins
$ 
```
Then run pluginCmd.py

**Comment by edreamleo** [comment] 2017-10-24 09:04
Thanks for the detailed report and attempts to pinpoint the problem.

**Comment by SegundoBob** [comment] 2017-10-26 00:24
I did the bisect by hand.  I had to modify my test code slightly.  I won't bother posting my modifications unless you request them.

The first commit that is bad is:
```
eebab8b
Leo 5.5, build 20170902113142, Sat Sep  2 11:31:42 CDT 2017
commit eebab8b471254fdf8b4f7897b339eae4da8047fd
Author: Edward K. Ream <edreamleo@gmail.com>
Date:   Sat Sep 2 11:31:41 2017 -0500

    It's no longer possible to bind keystrokes using k.registerCommand.
    The mod_scripting plugin calls k.bindLate to make very late key bindings.
    
    - k.registerCommand issues a warning if the user uses the deprected "shortcut" keyword arg.
    - Added k.bindLate. k.registerCommand calls it *without a shortcut*.
    - Removed "shortcut" keyword arg from all calls to k.registerCommand in Leo's core.
    - Updated unit tests accordingly.
    
    Leo build: 20170902113142
```

**Comment by edreamleo** [comment] 2017-10-27 13:52
On Wed, Oct 25, 2017 at 7:24 PM, SegundoBob <notifications@github.com>
wrote:

> I did the bisect by hand. I had to modify my test code slightly. I won't
> bother posting my modifications unless you request them.
>
> The first commit that is bad is:
>
Thanks for this.  This issue has been labeled "first".

Edward

**Comment by edreamleo** [comment] 2017-11-17 14:05
This works for me.  

Node 1:
Head: @command bug-560 @key=Shift-Ctrl-B
Body: print('bug-560')

Node2:
Head: execute bug-560
Body: c.k.simulateCommand('bug-560')

print-commands contains:
button: Ctrl+Shift+B     @command-bug-560

print-bindings contains:
@ button: Ctrl+Shift+B @command-bug-560

Am I missing something?

Edward

**Comment by tbnorth** [comment] 2017-11-17 14:48
I think the problem is that k.registerCommand (in a plugin) can't define commands that can be found by k.simulateCommand.  This was the issue with Ctrl-Shift-F for the Nav pane.  I think a workaround is for plugins to define commands with g.command.  Somewhere you made a comment along the lines of k.registerCommand having become too complex.

**Comment by edreamleo** [comment] 2017-11-17 15:08
On Fri, Nov 17, 2017 at 8:48 AM, Terry Brown <notifications@github.com>
wrote:

> I think the problem is that k.registerCommand (in a plugin) can't define
> commands that can be found by k.simulateCommand.
>
​Yes, that's what the title of the issue says.  I'll investigate this
aspect of the issue now.

But the example does work.​

Edward

**Comment by edreamleo** [comment] 2017-11-17 15:30
On Fri, Nov 17, 2017 at 9:08 AM, Edward K. Ream <edreamleo@gmail.com> wrote:

> I think the problem is that k.registerCommand (in a plugin) can't define
>> commands that can be found by k.simulateCommand.
>>
>
​Enable the ​testRegisterCommand.py plugin. This leo script works:

    c.k.simulateCommand('print-hello')

Executing the print-hello command from the minibuffer also works.

However, I have not been able to bind anything to the print-hello command.
That's the one and only bug that I see here.

Edward

**Comment by tbnorth** [comment] 2017-11-17 15:41
On Fri, 17 Nov 2017 15:30:16 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> On Fri, Nov 17, 2017 at 9:08 AM, Edward K. Ream <edreamleo@gmail.com>
> wrote:
> 
> > I think the problem is that k.registerCommand (in a plugin) can't
> > define  
> >> commands that can be found by k.simulateCommand.
> >>  
> >  
> ​Enable the ​testRegisterCommand.py plugin. This leo script works:
> 
>     c.k.simulateCommand('print-hello')
> 
> Executing the print-hello command from the minibuffer also works.
> 
> However, I have not been able to bind anything to the print-hello
> command. That's the one and only bug that I see here.

Right, I maybe shouldn't have mentioned k.simulateCommand.  The
original bug, as I remember it, was that a command created in a plugin
by k.registerCommand can't be bound by the user in myLeoSettings
@shortcuts.  I guess it was working if the plugin also specified the
binding, but that's seen as bad practice.  A fairly complete workaround
was just to use g.command instead of k.registerCommand in the plugin
(and not have the plugin do any binding).

Cheers -Terry

**Comment by edreamleo** [comment] 2017-11-17 17:00
> A fairly complete workaround was just to use g.command instead of k.registerCommand in the plugin.

As of cf2f7e2, the testRegisterCommand plugin defines the print-hello2 command using g.command. This demonstrates that bindings to the print-hello and print-hello2 commands have no effect.  I'll fix this soon, closing this issue and opening a new issue for clarity.

**Comment by edreamleo** [comment] 2017-11-17 17:12
I am going to close this issue. #579 focuses on what I believe is the real problem.

Please reopen this issue if necessary.

**Closed by edreamleo** 2017-11-17 17:12 UTC
Labels: Bug, First

**Comment by SegundoBob** [comment] 2017-11-17 19:39
I think you misunderstand what I'm complaining about. So far as I can tell, none of your tests involve defining a command in a plugin and then using the command defined in the plugin.

I was working on a plugin X that defined a command and used cmdr.k.registerCommand() to inform Leo-Editor about the command.  In a Leo-Editor file that enabled plugin X, I was calling c.k.simulateCommand() to execute the command defined and "registered" in the plugin.

This worked great up until commit eebab8b471254fdf8b4f7897b339eae4da8047fd.  Now even with the latest commit, the call to c.k.simulateCommand() fails with log pane error message:

`simulateCommand: no command for hello-world-p
`

Yet print-commands shows that there is a command hello-world-p!

I have updated gist

[simulateCommand: no command for \<command-defined-by-plugin\> ](https://gist.github.com/SegundoBob/49c421b2b28b17ff72b1507775a8c640)

which provides a very simple test case:

# Test Procedure
helloWorld.py is the test plugin.

Place helloWorld.py where Leo-Editor can find it as a plugin.

Open the attached pluginCmd.leo.

With the node with headline "Hello World" selected, Ctrl-B.

**Comment by edreamleo** [comment] 2017-11-17 23:03
On Fri, Nov 17, 2017 at 1:39 PM, SegundoBob <notifications@github.com>
wrote:

> I think you misunderstand what I'm complaining about. So far as I can
> tell, none of your tests involve defining a command in a plugin and then
> using the command defined in the plugin.
>
​The testRegisterCommand.py plugin shows two ways of defining commands.
Hand tests show that both tests work from the minibuffer or from using
k.simulateCommand.

This line in helloWorld.py is incorrect:

    cmdr.k.registerCommand('hello-world-p', None, hello_world)

It should be:

    cmdr.k.registerCommand('hello-world-p', hello_world)

The bug arises due to a revise signature for k.registerCommand.

Edward

**Comment by SegundoBob** [comment] 2017-11-17 23:46
Thank you.  My bug, not yours.

**Comment by LewisNeal** [comment] 2017-11-18 08:06
helloWorld.py is in my plugins folder. I opened pluginCmd.leo, with headline "Hello World" selected, Ctrl-B.

I get this error:
Leo Log Window
Leo 5.6, build 20171117105807, Fri Nov 17 10:58:07 CST 2017
Git repo info: branch = master, commit = cf2f7e2e5715
Python 3.6.3, PyQt version 5.9.2
Windows 10 AMD64 (build 10.0.15063) SP0
isPython3: True
caching enabled
reading: N:\leo\pluginCmd.leo
read outline in 0.13 seconds
exception executing command
Traceback (most recent call last):

  File "N:\git\leo-editor\leo\core\leoCommands.py", line 5621, in doCommand
    val = command(event)

TypeError: hello_world() takes 0 positional arguments but 1 was given

**Comment by edreamleo** [comment] 2017-11-18 09:55
On Sat, Nov 18, 2017 at 2:06 AM, LewisNeal <notifications@github.com> wrote:

> helloWorld.py is in my plugins folder. I opened pluginCmd.leo, with
> headline "Hello World" selected, Ctrl-B.
>
> I get this error:
>

​helloWorld.py is not an official plugin.  It was meant as an example.  I
think it's reasonable for you just to delete it.

Edward

**Comment by edreamleo** [comment] 2017-11-18 15:03
@SegundoBob >My bug, not yours.

I had a hand in it, because of the changed signature for k.registerCommand.  As of 1bd2cf9, k.registerCommand will warn if the "func" arg is None.

BTW, it turns out that several plugins, including mod_scripting.py must be allowed to call k.registerCommand with a non-empty shortcut, so no warnings about same are possible.  However, k.registerCommand no longer ever calls k.killBinding, which is correct, imo.
