### ISSUE TITLE
@auto and @auto-md not equivalent for .Rmd file

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#342] opened 2016-11-28 17:34 UTC
78413a4

Create a headline `@auto mydoc.Rmd` and do `refresh-from-disk`.  It looks ok to me, but Leo inserts @ignore.

When I remove @ignore and write, the written version has no headlines, although that doesn't seem to happen if I use @auto-md instead of just @auto, and yet plain @auto is recognizing .Rmd as markdown for import.

The insertion of ignore seems to go away with @auto-md.

Also, if I refresh from disk after writing the no headline version, Leo says:

```
Internal Leo error in bodyString
not unicode: '@others\n\nWarning: this node is ignored when writing this file.\n\n@language md\n@tabwidth -4\n'
Called from get_directives_dict_list,get_directives_dict,__get_b,bodyString
Please report this error to Leo's developers
@auto failed: @auto NNNM_manual.Rmd
```

Which seems odd, seeing the file's still valid markdown, just missing headings.

Everything seems fine when using @auto-md, *and* I really like the !headline feature, I had to give a pointless title to a couple of preamble sentences before, nice not to have to do that.

**Comment by edreamleo** [comment] 2016-11-29 18:45
Thanks for this report. These issues probably also apply to the leo_rst importer.  I should be able to resolve these soon.

**Comment by tbnorth** [comment] 2016-12-01 17:24
Just for completeness, at dd0e3fe3a I'm seeing the error report for @auto-md, I thought it was only coming up with @auto before, might be wrong:

```
reading: @auto-md NNNM_manual.Rmd

Internal Leo error in bodyString
not unicode: '@others\n\nWarning: this node is ignored when writing this file.\n\n@language md\n@tabwidth -4\n'
Called from get_directives_dict_list,get_directives_dict,__get_b,bodyString
Please report this error to Leo's developers
```

**Comment by edreamleo** [comment] 2016-12-02 13:32
There is a much worse problem with the present markdown import code: it confuses the `-` convention (for headlines) with `-` used in lists!

As always with importers, there are two parts to the problem:

1. How the importer reads files created *outside* of Leo.
2. How the importer reads files written by the corresponding writer plugin.

Clearly, the `-` conventions must be scrapped, or modified.

This looks like another case of the perfect-import tail wagging the dog. The writer should probably just write all headlines and body lines as they are.  The importer would probably best convert *all* sections to `#` sections, eliminating underlining lines.

The alternative is some kind of heroic escape convention.  Worse, remembering the "proper" underlining in uA's would make it impossible for new nodes to contain underlined sections.

`-` and `=` underlinings in markdown would seem to have no real purpose, especially in Leo.  If the perfect import check ignored underlining differences (which might be non-trivial), then in most cases users won't care, or even notice...

**Comment by edreamleo** [comment] 2016-12-04 11:22
at.createWritersData is being called way too often.  Instead, Leo's startup code should create the import tables.  There are other problems, revealed by recently-failing unit tests. This issue is moving to the top of the priority list.

**Comment by tbnorth** [comment] 2016-12-05 16:09
Update Leo to
Leo 5.4, Mon, 5 Dec 2016 05:00:52 -0600
Git commit: after 48242838

@auto-md NNNM_manual.Rmd read fine

Changed to @auto NNNM_manual.Rmd and did refresh from disk:

```
Internal Leo error in bodyString
not unicode: '@others\n\nWarning: this node is ignored when writing this file.\n\n@language md\n@tabwidth -4\n'
Called from writeFile,makeCacheList,__get_b,bodyString
Please report this error to Leo's developers
```

I wonder if that's a refresh from disk error (cache) rather than an importer error?  Just intruding when I'm trying to describe what I'm seeing here.

Still losing all the headlines writing with just @auto, not @auto-md, so to your .rmd vs. .Rmd question...

(a) it appears to make do difference, still losing headlines, and (b) it's harder than you'd think to rename .Rmd .rmd on this case insensitive NTFS filesystem :-)

**Comment by edreamleo** [comment] 2016-12-08 10:33
On Mon, Dec 5, 2016 at 10:09 AM, Terry Brown <notifications@github.com>
wrote:

> @auto-md NNNM_manual.Rmd read fine
>
​Good.  That bypasses the dubious test in the leoAtFile​.py read logic.

> it's harder than you'd think to rename .Rmd .rmd on this case insensitive
> NTFS filesystem :-)
>
​21b09ed​

​adds .Rmd to the list of list of extensions presumed to be markdown
extensions.  Does that result in @auto working for .Rmd files?

EKR

**Comment by edreamleo** [comment] 2017-02-05 10:56
Terry, what is the status of this issue?

In other words, does 21b09ed​ fix this issue?

**Comment by tbnorth** [comment] 2017-02-05 21:33
Will try and check soon.

**Comment by tbnorth** [comment] 2017-02-06 18:06
It does not appear to be fixed.  I'm at 22a74c2db. When I change `@auto-md` to `@auto` for an `.Rmd` file, change the `@auto-md` to `@auto` and write the file (I think that's where the problem lies) I see a diff like this (note addition at end of diff):

```diff
diff --git a/src/Introduction.Rmd b/src/Introduction.Rmd
index 6733fe3..ae91eab 100644
--- a/src/Introduction.Rmd
+++ b/src/Introduction.Rmd
@@ -1,7 +1,5 @@
-#Introduction

-##Background

 The Great Lakes are a precious source or drinking water, recreation, and
 transport. They are regional and national treasures.
@@ -76,7 +74,6 @@ divide the nearshore into some 30 regions. Our study site is shown on
 the eastern shore of Lake
 Michigan.](img/glahf_regions.{EXT}){#fig:regions}

-##FIXME: Papers to reference
  - [ ] @Rao2007
  - [ ] @Luscz2015
  - [x] @Wang2015, @Forsyth2016, GLAHF defines in lake "regions"
@@ -101,7 +98,6 @@ Michigan.](img/glahf_regions.{EXT}){#fig:regions}
  - [ ] @Yurista2015
  - [ ] @Chapra1977,@Chapra2012

-##Objectives


 “How do watershed loads impact the nearshore at different spatial/temporal scales ~~in South East Lake Michigan~~ at a regional level?”
@@ -137,3 +133,6 @@ Overall work plan:

 Current paper step 1-2.

+
+Warning: this node is ignored when writing this file.
+
```

**Comment by edreamleo** [comment] 2017-03-04 15:22
Part of the problem is that specialized `@auto` nodes ignore the top-level node.  This causes no end of confusion.  There may be a reason for it, but it can't be good enough ;-)

**Comment by tbnorth** [comment] 2017-03-04 20:21
It's a place to put @rst directives that don't get written in the sentinel free external file, but I don't really use rst, certainly not the special directives - and that only applies to rst, not other formats... anyway, best reason I can think of but not a feature I'd miss at all.

**Comment by edreamleo** [comment] 2017-03-05 11:12
Everything works for me on a simple test file. Please post the test file you are using.

**Comment by edreamleo** [comment] 2017-03-11 13:06
I am going to close this.  Please reopen as needed.

**Comment by tbnorth** [comment] 2017-03-21 18:57
Sorry about the delay. Problem persists.

Editing the attached file in a @auto-md node, all works as expected, apart from maybe a missing blank line between "# Results" and "Discuss the results.".

In a plain @auto node, when writing, "# Results" is missing from the output, and "Warning: this node is ignored when writing this file." in *included* in the output.

(had to add .txt extension for GitHub, remove that first)

Attached file: [something.Rmd.txt](https://github.com/leo-editor/leo-editor/files/859344/something.Rmd.txt)

```
Leo 5.5b1, build 20170321132242, Tue, Mar 21, 2017  1:22:42 PM
Git repo info: branch = master, commit = 9dc01ffeaecd
Python 2.7.5, PyQt version 4.8.5
Windows 7 AMD64 (build 6.1.7601) SP1
```

**Comment by edreamleo** [comment] 2017-03-21 20:24
On Tue, Mar 21, 2017 at 1:57 PM, Terry Brown <notifications@github.com>
wrote:

> Sorry about the delay. Problem persists.
>
> Editing the attached file in a @auto-md node, all works as expected, apart
> from maybe a missing blank line between "# Results" and "Discuss the
> results.".
>
> In a plain @auto <https://github.com/auto> node, when writing, "#
> Results" is missing from the output, and "Warning: this node is ignored
> when writing this file." in *included* in the output.
>
> (had to add .txt extension for GitHub, remove that first)
>
> Attached file: something.Rmd.txt
> <https://github.com/leo-editor/leo-editor/files/859344/something.Rmd.txt>
>
​Thanks.  We'll get this right shortly.

Edward

**Comment by edreamleo** [comment] 2019-01-20 18:54
I am going to close this item.  Please reopen if necessary.

**Closed by edreamleo** 2019-01-20 18:54 UTC
Labels: Bug, Waiting
