### ISSUE TITLE
After I changed py file contents by gvim or pycharm, the @file contents were not changed

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1043] opened 2019-01-02 05:22 UTC
After I changed py file contents by gvim or pycharm, the @file contents were not changed in body panel. Note: After I did Reopen .leo file or `refresh from disk`, it did not take effect.

Now I have to continue write code in pycharm or gvim.

How can I go back to leo-editor with correct contents in @file node except import py file again?

**By some test, I found delete clone node, then recreate a clone node, then it runs correct now!**

***
Leo Log Window
Leo 5.8.1 devel, build 20181227100358, Thu Dec 27 10:03:57 PST 2018
Git repo info: branch = devel, commit = b9c0ac6849c3
Python 3.6.7, PyQt version 5.11.2
linux
isPython3: True
import-jupyter-notebook requires nbformat package

**Comment by edreamleo** [comment] 2019-01-07 11:18
This works for me.  I doesn't matter what editor you are using: Leo scans for all changed external files at idle time.  Make sure the value of `@bool check_for_changed_external_file` is True.

**Comment by wangzhaohe** [comment] 2019-01-10 03:04
Perhaps It was produced by many nested cloned nodes. So now I only use clone node with one level.

**Comment by edreamleo** [comment] 2019-01-15 19:46
I'll continue to look into this as I fix several related issues.

**Comment by edreamleo** [comment] 2019-01-19 13:47
I am going to close this.  In some ways it may be a duplicate of #445 or #981.

**Closed by edreamleo** 2019-01-19 13:47 UTC
Labels: Bug, Duplicate, First
