### ISSUE TITLE
Allow multiple instances of @outline-data tree-abbreviations

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#549] opened 2017-09-08 20:28 UTC
Discussed [here in the forums](https://groups.google.com/d/msg/leo-editor/t6gCmczRiM4/gYLOp3FVAwAJ).

- Perhaps have a global tree in the myLeoSettings file and a local tree in a 'regular' Leo file.
- Or, better yet, simply allow later trees to load *without* disabling previous ones. This would have the added benefit of organizing large lists into multiple trees (as can be done with the other abbreviation modes).

**Comment by edreamleo** [comment] 2018-05-23 12:26
This is a duplicate of #904, which has been closed.

**Closed by edreamleo** 2018-05-23 12:26 UTC
Labels: Enhancement
