### ISSUE TITLE
Spontaneous clones when using <<sections>>

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#89] opened 2014-11-04 17:32 UTC
c.f. https://bugs.launchpad.net/leo-editor/+bug/1282362 (sorry, was just replying to email, didn't notice it was to "the old place"!) Recap here (of just the new Oct 2014 stuff):

>> [Matt sayeth]
>> [that Launchpad bug] sounds similar to ...
>>
>>That's weird, I swear I created a bug this weekend about spontaneous
>>clones. I spent an hour or more writing it up, reducing to smallest
>>reproducible test case and screenshots and all. Anyway, I wasn't using
>>@shadow, here's the file, non-shortened version, which produces spontaneous
>>clones:
>> https://github.com/maphew/apt/blob/master/apt.py
>>
>>![apt-dev leo in b__code_2014-11-03_15-19-09](https://cloud.githubusercontent.com/assets/486200/4904562/901048de-6448-11e4-82b3-7d4d4d5fdb46.png)

> [Edward respondeth]
>Thanks for this. I see the clones when I import apt.py, but I'm not
>convinced this is a clone issue.
>
>Indeed, apt.py contains six copies of the following sentinel::
>
>#@+middle:maphew.20141031145131.3: ** __name__ __main__ runner
>
>+middle lines are part of the @others logic (I forget the details). I would
>guess this is a problem with either the read or write logic, or both.
>
>I see the imported outline, but without the original .leo file I have no
>way of knowing what you really intended. Can you send to me?
>
>The following works::
>
```
>Define main (in a separate node) as::
>
    def main():
        <<globals>>
        <<parse command line>>
        <<post-parse globals>>
        <<run the commands>>
        <<wrap up>>
>
>And then do the typical::

    if __name__ == "__main__":
        main()

>Clones go away.
>
>Yes, there is a problem, but I'm pretty sure it has to do with @others
>expansion, not clones. The @others expansion logic at the top-level node
>is probably clashing, in some weird way, the the section references.
>

**Comment by edreamleo** [comment] 2015-02-27 09:50
B1 seems like an appropriate target for this bug.  I should not have left it lying around for so long.

**Comment by edreamleo** [comment] 2015-03-06 14:40
@maphew Matt, how important is this issue for you?  I'd like to continue to ignore it if possible :-)

**Comment by edreamleo** [comment] 2016-04-06 13:48
This is a duplicate of [#132](https://github.com/leo-editor/leo-editor/issues/132). It arises because of @+middle sentinels, which have just been eliminated.

**Closed by edreamleo** 2016-04-06 13:48 UTC
Labels: bug, status:duplicate
