### ISSUE TITLE
execute-external-file puzzles and possible bug

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#3195] opened 2023-03-08 00:18 UTC
Thomas Passin,

Today I tried to replace the "execute external file" code you posted here [Forum Topic](https://groups.google.com/g/leo-editor/c/TuUEA452Rbo/m/tts4qjSFBQAJ?pli=1).  The code you posted continues to work as I expect.  The code you put in leocommands.py does not work as I expect. 

`Alt+X, execute-external-file` seems to fail to find the "@file"  at the currently selected position.  It always just starts a new terminal.  And instead of terminating the terminal  on the first carriage return, the terminal stays open till an "exit" is executed.

### Test System
```
Leo Log Window
Leo 6.7.3-devel, devel branch, build 3f91d8c67f
2023-03-06 12:24:49 -0600
Python 3.9.16, PyQt version 5.15.2
linux

```

Regards,
SegundoBob

**Comment by tbpassin** [comment] 2023-03-08 01:05
Hmmm, works for me using 
```
Leo 6.7.2-devel, devel branch, build 5f2578c58b
2023-02-27 13:53:28 -0500
Python 3.10.9, PyQt version 6.4.1
Windows 10 AMD64 (build 10.0.19044) SP0
```
and also using
```
Leo 6.7.2-devel, devel branch, build 5f2578c58b
2023-02-27 13:53:28 -0500
Python 3.10.6, PyQt version 6.3.2
linux
```
I'll update to the current 6.7.3 and see what's what.  I did not change anything about the command so far as I know.

"It always just starts a new terminal." -- do you mean the terminal opens but the program does not launch?

Also, please remind me what version of Linux you are using.

**Comment by tbpassin** [comment] 2023-03-08 01:34
Works for me launching a Python file using 
```
Leo 6.7.3-devel, devel branch, build 3f91d8c67f
2023-03-06 12:24:49 -0600
Python 3.10.6, PyQt version 6.3.2
linux
```

My Linux VM is `Ubuntu 22.04.2 LTS`.

What language is your external file in?

**Comment by tbpassin** [comment] 2023-03-08 15:00
With the Ubuntu VM, the command is failing to launch my non-python test files - using ruby, julia, and lua.  Going back to my Manjaro VM, now upgrade to Leo 6.7.3, the non-python test files do not get launched, either.

Before I submitted the PR for this command, I had tested it with success on all of my VMs for all of the non-python external files.  So something has changed.  I will work on tracking it down.

**Comment by SegundoBob** [comment] 2023-03-08 20:14
Thomas,

I use "Ubuntu 20.04.5 LTS".
You use "Ubuntu 22.04.2 LTS.".

I use "Python 3.9.16".
You use "Python 3.10.6".

I use "PyQt version 5.15.2".
You use "PyQt version 6.3.2".

> "It always just starts a new terminal." -- do you mean the terminal opens but the program does not launch?

Yes, the terminal opens, but no program launches.

I have only tried external Bash files and external Python files.

Now I have made a button to execute "c.executeMinibufferCommand('execute-external-file')".  This button fails in the same way that executing execute-external-file in the Minibuffer fails.  I run my tests by starting Leo-Editor in a terminal.  During my tests, no errors are output to the terminal.

I doubt that our different results are caused by any of the differences listed above.  I have no idea what is wrong.

Regards,
SegundoBob

**Comment by tbpassin** [comment] 2023-03-08 21:06
For bash files, add a shebang line as the first line:
`#! /usr/bin/bash`

(or whatever the actual path to bash is). You will also have to mark the file as executable.  If the command cannot find a known processor for the external file, it checks to see if there is a shebang line.  In the case of bash files, I decided not to assume that all files with no extension should be run by the shell - since there are many executable files that do not have extensions but are not bash files.

The command is able to read processor assignments from an `@data` node, but in the current Leo/Ubuntu incarnation, it's not working for me.  I'll look into that.  The shebang line works, though, and is not limited to just bash files.

I don't know why external python files aren't getting launched, and I also don't know why you aren't seeing any error messages, whether in Leo's terminal or in Leo's log pane.

**Comment by tbpassin** [comment] 2023-03-08 23:16
All right, I've got this thing figured out, I think.  

1. Bash scripts didn't launch unless they have a shebang line.  This won't change.

2. Bash scripts with a ".bash" extension didn't launch even after I added bash to the `@data` node.  This is because Leo was reporting the language as "shellscript" even though my test file _simple.bash_ did not have an @language directive.  I have added "shellscript" as one of the languages, to be executed by bash unless this is overridden in the `@data` node.

3. The processing of the `@data` node for adding new file extensions and processors had a bug.

I will put in a PR with the fixes, after checking them on a few other Linux VMs with different OSs.

Except that I still don't know why your external Python file isn't launching.  Can you send me its subtree, or can you send me a simplified version that isn't launching?

**Comment by tbpassin** [comment] 2023-03-09 04:25
Attached is my test suite for the execute-external-file command. 

[launcher-test-files.zip](https://github.com/leo-editor/leo-editor/files/10927679/launcher-test-files.zip)

These work on Linux and Windows (even, surprise! the `.bash` file - the command finds the copy of _bash.exe_ that came with my _git_ installation ) - of course, you need to have julia, lua, and ruby installed to run them all).

Please test them and let me know what happens.

**Comment by SegundoBob** [comment] 2023-03-12 23:25
Thomas,

The code you posted here [Forum Topic](https://groups.google.com/g/leo-editor/c/TuUEA452Rbo/m/tts4qjSFBQAJ?pli=1)  works for me and your execute-external-file code in the Leo-Editor core does NOT work for me because you changed determining the terminal-program to use.

Your "Forum Topic" code runs terminal program xfce4-terminal.

Your execute-external-file code runs terminal program /usr/bin/rofi-sensible-terminal, which is a wrapper script in Bash.  See attached [rofi-sensible-terminal](https://github.com/leo-editor/leo-editor/files/10952317/rofi-sensible-terminal.txt).  Note that I had to give this file the .txt extension in order to attach it.  On my system it launches xfce4-terminal, but it apparently losses your designation of the program to run and when to exit the terminal. [rofi-sensible-terminal man page](https://manpages.debian.org/testing/rofi/rofi-sensible-terminal.1.en.html)

This ends my interest in execute-external-file.

### Answering Your Questions

I have always had the shebang line in all my script files.

launcher-test-files.zip does NOT include the external files referenced by @file.  So I can't run your tests: launcher-test.jl and launcher-test.py.

I don't have lua installed.  Hence, your tests factorial.lua results in this log pane error message:

`No processor for /home/bob/Temp/leo/factorial.lua`

launcher-test.rb results: no error reported anywhere, terminal opened, no script executed, terminal remains open till "exit" executed.

test.bash results in this log pane error message:

`No processor for /home/bob/Temp/leo/test.bash`

Because test.bash does not have a shebang first line.

So I added the shebang first line.

Then test.bash result:  no error reported anywhere, terminal opened, no script executed, terminal remains open till "exit" executed.

### New test system (same results as old test system):

```
Leo 6.7.3-devel, devel branch, build b05953fe5b
2023-03-10 07:02:27 -0600
Python 3.9.16, PyQt version 5.15.2
linux
Ubuntu 22.04.2 LTS.

```

Regards,
SegundoBob

**Comment by tbpassin** [comment] 2023-03-13 03:36
I'm stumped why you aren't seeing any output in the terminal.  It's been working without fail when I use it in half a dozen different Linux distros (running in VMs).

For not having Lua, etc., I hoped that you might install the missing ones to help with testing, but I understand your not wanting to do that.

For the external files,  they were all `@clean files` so it should have been possible to have Leo write them out to their intended destinations (which of course you could edit to different locations if you needed to.  I think the _write-at-file-nodes_ command will do that even though they are `@clean` files.  If not, you can add a space to each one, then save the outline.

Not launching a file with a _.bash_ extension was caused by a Leo feature that surprised me - Leo assigns a file "kind" of "shellscript" to those files, and that kind of file did not have a processor specified in the lookup tables.  Newer changesets of Leo have this provided for, and _.bash_ files do get launched without a shebang - at least on my test systems.

I will go back and look at differenced between the earlier script and the current command to see about the "/usr/bin/rofi-sensible-terminal".  I could always have the command check for well-known terminals  first before trying to deduce one, and the _xfce4-terminal_ would certainly be included.  I hoped not to have to hardcode any of them because there so many possibilities among all the various distros, especially as customized by their users.  However, I did break down and added two hard-coded terminals, so I might as well go ahead an add a few more of the most common ones.

The newer version of the command lets you specify your desired terminal in the `@data run-external-processor-map` setting file, like this (uncomment the line to make it active: 
```
# Optionally specify a Linux terminal here (e.g., konsole)
TERMINAL
# konsole
```
This is documented in the command's docstring.

I want to thank you for helping me test the command.  I know it's frustrating for it not to work right.  Of course, it's hard for me to debug since my distros aren't acting the same as yours.

Would you be willing to run this script for me and tell me what terminal it returns?  It's part of the code from the command, except I added that odd terminal of yours.  On my Ubuntu VM it returns gnome-terminal.

```
import subprocess

def getTerminalFromDirectory(dir: str) -> str:
    BAD_NAMES = ('xdg-terminal', 'setterm', 'ppmtoterm', 'koi8rxterm', 'rofi-sensible-terminal')
    TERM_STRINGS = ('*-terminal', '*term')

    for ts in TERM_STRINGS:
        cmd = f'find {dir} -type f -name {ts}'
        proc = subprocess.run(cmd, shell=True, capture_output=True)
        terminals = proc.stdout.decode('utf-8')
        for t in terminals.splitlines():
            bare_term = t.split('/')[-1]
            if bare_term not in BAD_NAMES:
                return t
    return None

g.es(getTerminalFromDirectory('/usr/bin'))
```

On my Ubuntu VM it returns _/usr/bin/gnome-terminal_, and that's what the command uses.   As you can see, it takes the first result it finds in _/usr/bin_, since there really isn't any way to know which one would be "the best".

I will also change the command to prefer the hard-coded ones first.  Currently it uses them as a fallback if the other methods of identifying a terminal fail.

**Comment by tbpassin** [comment] 2023-03-13 04:43
I may have figured out why @SegundoBob hasn't been seeing output in the terminal.  The _execute-external-file_ command has been using an unexpected, uncommon terminal.  The command needs to find out what command line parameters to use to execute the launch command in the shell.  It does this by reading the --help output.

It's possible that for this terminal, the help output is different enough that the command cannot figure out the right parameters.

I just submitted a PR that should fix these problems by:

1. Trying to use a preferred terminal first instead of as a fall-back;
2. Adding more terminals to the preferred list;
3. Adding the terminal @SegundoBob mentioned to the banned-terminal list.

**Comment by tbpassin** [comment] 2023-03-13 15:06
From the _[rofi-sensible-terminal man page](https://manpages.debian.org/testing/rofi/rofi-sensible-terminal.1.en.html)_:

```
It tries to start one of the following (in that order):

$TERMINAL (this is a non-standard variable)
x-terminal-emulator
urxvt
...
```
This explains the problem, then, because I have found that _x-terminal-emulator_ varies too much in its launching parameters to be reliable, and $TERMINAL, which doesn't even exist on many system, would also be questionable.

You would think that with POSIX, terminal behavior would be dependable from one distro and terminal to another, but it isn't.

BTW, I changed the code in the preliminary script because it wasn't picking up working combinations of terminal/parameters with several Linux distros I tried.

**Comment by edreamleo** [comment] 2023-03-13 15:41
@tbpassin What is the status of this issue. Did PR #3204 fix things?

**Comment by tbpassin** [comment] 2023-03-13 17:24
"Did PR https://github.com/leo-editor/leo-editor/pull/3204 fix things?"

I can't tell, because I myself didn't get any errors even before the change.  I'm pretty confident it will fix things for SegundoBob, but unless he tries the new version out, we won't know for sure.

A potential future issue could be that some distro or another - there are so many - or someone "tweaking" theirs with some pet terminal, etc. - could fail to work because theirs doesn't work like most of the main distros.

Here's how the command chooses a terminal with this current release.  The terminal has to run a shell that has its own command line to launch our external file.  Typically a terminal uses `-e` or `--` , or either, to execute a command, but not all terminals do.

1. Check the `@data` setting for a terminal to use;
2. If none, use one of the preferred terminals if present;
3. If none are present, look in /usr/bin and then in /bin for a program named *-terminal or *term.  Use the first one found that isn't on the list of "bad" terminals.
4. get the terminal's `--help` message and parse it for the command line parameter to execute a program.

We need step 4 because the various terminals don't all use the same parameter.  Also, I found some that warned that the parameter might change in the future, so we can't depend entirely on hard-coded parameters.

The above works on every distro/terminal combo I have set up a VM for, around seven or eight in all.  I suspect that step 4 failed in SegundoBob's case - it's the only way I can understand what he has experienced.  With the new PR, the command will use the right terminal for him (_xfce4-terminal_), and succeed at finding the correct parameter to run the program to be launched.

**Comment by edreamleo** [comment] 2023-03-13 20:05
@tbpassin Thanks for the heads up. I'll wait for you to close this issue.

**Comment by SegundoBob** [comment] 2023-03-13 21:02
Thomas,

The code you posted in [Your Post](https://github.com/leo-editor/leo-editor/issues/3195#issuecomment-1465461047) and requested that I run it, prints to the log pane:

`/usr/bin/xfce4-terminal`

Regards,
SegundoBob

**Comment by SegundoBob** [comment] 2023-03-13 21:10
Thomas,

In [Your Post](https://github.com/leo-editor/leo-editor/issues/3195#issuecomment-1466327084)  you write:

> This explains the problem, then, because I have found that _x-terminal-emulator_ varies too much in its launching parameters to be reliable

This does **NOT** explain the behavior I see.  As I wrote, on my machine your code runs rofi-sensible-terminal which in turn runs _xfce4-terminal_.  This has nothing to do with _x-terminal-emulator_ .

Regards,
SegundoBob

**Comment by tbpassin** [comment] 2023-03-13 22:13
SegundoBob,

The man page for _rofi-sensible-terminal_ says that it tries a long list of terminals in order, and _x-terminal-emulator_ is right at the top of the list.  So according to that, _x-terminal-emulator_ would get run in preference to _xfce4-terminal_, if it's on your system, otherwise one of the others.  Most systems have _x-terminal-emulator_, but it can be difficult to impossible to extract the right command line parameter  to use.

On my Debian system, _x-terminal-emulator_ exists and I assume it's on yours too.  So I think that in the previous version of the _execute-external-file_, that's the terminal that got run by _rofi-sensible-terminal_.  Chances are that the command would not know what parameter to use to execute the external program with the shell.  That would cause the terminal to open but not display any output (because it wasn't able to run the shell command).

BTW, how did you set up your Debian system to have _rofi-sensible-terminal_ and xfce?  My Debian VM has Cinnamon with _gnome-terminal_. (It's _Debian GNU/Linux 11 bullseye (x86-64)_).

**Comment by tbpassin** [comment] 2023-03-13 22:14
I just noticed that the description of the `@data` setting contents has gotten out of sync.  I'll have to fix that.  I think I will also add _x-terminal-emulator_ to the list of disallowed terminals.

**Comment by tbpassin** [comment] 2023-03-14 03:16
PR https://github.com/leo-editor/leo-editor/pull/3206 addresses a bug in reading terminal setting in the `@data` setting, honors SegundoBob's request to identify what terminal was read from `@data` setting if that terminal cannot be found on the computer.

It also fixes typo errors in two docstrings about the format for some entries in the optional `@data` setting.

**Closed** 2023-03-14 10:18 UTC

**Comment by SegundoBob** [comment] 2023-03-14 18:17
Thomas,

[Your Post](https://github.com/leo-editor/leo-editor/issues/3195#issuecomment-1467040416) rightly conjectures that  _x-terminal-emulator_exists on my system, but not in the simple form you seem to think.

```
$ ls -l /usr/bin/x-terminal-emulator
lrwxrwxrwx 1 root root 37 Feb 22  2018 /usr/bin/x-terminal-emulator -> /etc/alternatives/x-terminal-emulator

$ ls -l /etc/alternatives/x-terminal-emulator
lrwxrwxrwx 1 root root 31 Feb 22  2018 /etc/alternatives/x-terminal-emulator -> /usr/bin/xfce4-terminal.wrapper

```

File `/usr/bin/xfce4-terminal.wrapper` is a 67-line Perl script that ends with _exec('xfce4-terminal',@args);_

As I have written many times, on my system the end result is that _xfce4-terminal_launches but no script is executed.

Regards,
SegundoBob

**Comment by tbpassin** [comment] 2023-03-14 19:12
> As I have written many times, on my system the end result is that _xfce4-terminal_launches but no script is executed.

I realize that, but I have found that the wrappers do not always output the same help messages that the unwrapped executable does.  If the help message doesn't have a line that gives a parameter (e.g., "-e") and says it is the executable flag, then the _execute-external-file_ command won't know what parameter to use. The result will be what you see - the terminal launches but nothing else happens.

Anyway, the new version of the script looks first for a list of preferred terminals, which includes _xfce4-terminal_, and is able to parse its help message and find the parameter to use.  The _x-terminal-emulator_ is disallowed if it happens to be found, in case none of the preferred ones are on the system.

Would you tell me how you set up Debian with xfce?  If I can build a VM with the same configuration as yours, I should be able the find the issue more effectively.  The VM that I have with xfce is Manjaro and the command works fine on it.

I also installed xfce on my Linux Mint VM (originally installed only with Cinnamon), and the command finds _xfce-terminal_ and successfully runs all my test programs.

**Comment by SegundoBob** [comment] 2023-03-14 20:37
Thomas,

### Test System
```
Leo 6.7.3-devel, devel branch, build f96d08744e
2023-03-14 05:14:34 -0500
Python 3.9.16, PyQt version 5.15.2
linux
Ubuntu 22.04.2 LTS
```
### Test Results
Your command  `execute-external-file` now works for me with and without specifying the terminal to use in a  `@data_node`.   When I intentionally specify a non-existent terminal in the  `@data `node, the error message shows the bad terminal name.

### Your Question
`Would you tell me how you set up Debian with xfce?`

I installed Xubuntu.  Then I replaced the window compositor with i3wm.   Debian is behind Ubuntu.  I don't directly deal with Debian.

Regards,
SegundoBob

**Comment by tbpassin** [comment] 2023-03-14 23:21
Excellent, thanks so much for helping me with this!

As one of the VMs for testing, I created one with Kubuntu, but not Xubuntu.  Maybe I'll try that one.  So far I like Manjaro the best.  It seems snappier, somehow.  But I've had trouble getting some services set up that I generally need for other testing, including MySQL and Tomcat.  On Linux Mint, Debian, and Ubuntu they have always worked right off the bat.
