### ISSUE TITLE
Syntax coloring issue: @language directive does not colorize child nodes anymore

### ISSUE THREAD

**Issue by alacnorr** [leo-editor/leo-editor#393] opened 2017-02-01 11:33 UTC
system info
------------
Leo 5.4, build 20170131181828, Tue Jan 31 18:18:28 CST 2017
Git repo info: branch = master, commit = 588dc01ebd09
Python 3.6.0, PyQt version 5.7.1
Windows 10 AMD64 (build 10.0.14393) SP0

issue description
------------------
The @language directive only colorizes the root node in which it is written.
It does not colorize child nodes anymore.
This behavior change appeared after upgrade to build 20170131181828.

**Comment by edreamleo** [comment] 2017-02-01 14:15
Thanks for this report. My apologies for the recent problems.

In effect, this is a duplicate of #389, which I reopened a few hours ago. The effects are not exactly as you describe, and the fix for this and #389 are the same. As a result, I am going to mark this as a duplicate issue and close it.

**Closed by edreamleo** 2017-02-01 14:15 UTC
Labels: Bug, status:duplicate

**Comment by edreamleo** [comment] 2017-02-01 16:49
Fixed at 9c24a404a.  Please reopen #389, not this one, if there problems.
