### ISSUE TITLE
Leo crash: AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1466] opened 2019-12-22 23:14 UTC
Opening some leo files hard crashes Leo.

**EKR**: As reported in #1464: 

rev 1667e84 2019-12-18 18:54:47 is good
rev c9c766e 2019-12-18 19:21:40 is bad.

_Leo 6.2-b1-devel, devel branch, build 016867f5ad
2019-12-21 21:39:47 -0800
Python 3.6.8, PyQt version 5.14.0
Windows 10 AMD64 (build 10.0.18362) SP0_

N:\git\leo-editor>launchleo.py

--global-docks: False

Empty setting name in False
set parent @settings
Leo 6.2-b1-devel, devel branch, build 016867f5ad
2019-12-21 21:39:47 -0800
n:/git/leo-editor/leo/plugins/qmlnb/qml/leonbmain.qml: Network error
n:/git/leo-editor/leo/plugins/qmlnb/qml/leonbmain.qml: Network error
can not open c:/test/iframe.html
read only: c:/test/iframe.html
Traceback (most recent call last):
  File "N:\git\leo-editor\leo\plugins\qt_frame.py", line 3755, in qt_add_command_callback
    return command()
  File "N:\git\leo-editor\leo\core\leoCommands.py", line 3242, in add_commandCallback
    val = command()
  File "N:\git\leo-editor\leo\core\leoApp.py", line 3658, in recentFilesCallback
    c.openRecentFile(fn=name)
  File "N:\git\leo-editor\leo\commands\commanderFileCommands.py", line 860, in openRecentFile
    c2 = g.openWithFileName(fn, old_c=c)
  File "N:\git\leo-editor\leo\core\leoGlobals.py", line 3906, in openWithFileName
    return g.app.loadManager.loadLocalFile(fileName, gui, old_c)
  File "N:\git\leo-editor\leo\core\leoApp.py", line 3295, in loadLocalFile
    c = lm.openFileByName(fn, gui, old_c, previousSettings)
  File "N:\git\leo-editor\leo\core\leoApp.py", line 3333, in openFileByName
    ok = lm.readOpenedLeoFile(c, fn, readAtFileNodesFlag, theFile)
  File "N:\git\leo-editor\leo\core\leoApp.py", line 3502, in readOpenedLeoFile
    readAtFileNodesFlag=readAtFileNodesFlag)
  File "N:\git\leo-editor\leo\core\leoFileCommands.py", line 699, in openLeoFile
    silent=silent,
  File "N:\git\leo-editor\leo\core\leoFileCommands.py", line 575, in getLeoFile
    recoveryNode = fc.readExternalFiles(fileName)
  File "N:\git\leo-editor\leo\core\leoFileCommands.py", line 659, in readExternalFiles
    c.atFileCommands.readAll(c.rootPosition(), force=False)
  File "N:\git\leo-editor\leo\core\leoAtFile.py", line 476, in readAll
    at.readFileAtPosition(force, p)
  File "N:\git\leo-editor\leo\core\leoAtFile.py", line 530, in readFileAtPosition
    at.read(p, force=force)
  File "N:\git\leo-editor\leo\core\leoAtFile.py", line 360, in read
    FastAtRead(c, gnx2vnode).read_into_root(contents, fileName, root)
  File "N:\git\leo-editor\leo\core\leoAtFile.py", line 3668, in read_into_root
    contents = contents.replace('\r','')
AttributeError: 'NoneType' object has no attribute 'replace'
[end]

**Comment by LewisNeal** [comment] 2019-12-23 01:01
Crash still happens using default leoSettings.leo

**Comment by LewisNeal** [comment] 2019-12-23 01:35
If I load file using File>Recent Files, after 1 sec a blue spinning ring appears briefly, then Leo crashes before the file appears.
However using File>Open-outline the file opens.

**Comment by btheado** [comment] 2019-12-23 15:36
This is a duplicate of #1464. That issue has more details showing a working and non-working leo commit as well as a workaround.

Leo is throwing this error when the outline has an @ file node, but the corresponding file on the filesystem doesn't exist. For a workaround you can either go back to an earlier version of leo or create dummy files on the filesystem for which there are @ file nodes.

**Comment by edreamleo** [comment] 2019-12-24 10:42
Fixed at rev eabce7e.  Tested on missing @file and @shadow nodes.

**Closed by edreamleo** 2019-12-24 10:42 UTC
Labels: Bug, First
