### ISSUE TITLE
Possible very mysterious @file failure

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#1360] opened 2019-09-30 00:52 UTC
This seems too bizarre to be true, but if it is, it is a very serious problem.

Please unzip [2019-09-21-Phantom-NewHeadline.zip](https://drive.google.com/file/d/1IfoVXgq4QQZw3_8yj4koIP0NC5--8yfn/view?usp=sharing) 80.8 KiB.  It is on my Google Drive, because the github gist web interface only allows text files.

### This is what I observed:

code.leo would not write "@file test07.py".
Changing the name didn't help.
Moving the node didn't help.
Changing the contents of test07.py didn't help.
When I closed code.leo, I lost all my work in test07.py because it was not written to disk and it was not kept in code.leo
I remade test07.py under the same vnode as previous.
code.leo would not write test07.py.
So I copied not retaining GNX's the @file test07.py subtree to a new file xxx.leo.
xxx.leo wrote test07.py correctly.
I opened code.leo and even though test07.py now existed, code.leo showed its "@file test07.py" subtree completely empty.
I rebooted my system.
I opened code.leo and even though test07.py now existed, code.leo showed its "@file test07.py" subtree completely empty.
I looked at code.leo with emacs and with ghex.  The file contents, and the "@file test07.py" node in particular, looked correct.
I copied code.leo to atFileFailure01.leo.
I used xxx.leo to change test07.py while I also had code.leo open.  This popped up the "test07.py" changed outside Leo-Editor".  I chose load the changes.  This populated the "@file test07.py" subtree correctly.
Ever after, code.leo worked correctly: reading and writing test07.py as expected.
atFileFailure01.leo still fails to read test07.py even though it exists.
The "@file test07.py" node has the same gnx bob.20190929163422.1 in code.leo, xxx.leo, and atFileFailure01.leo.

### Console after opening atFileFailure01.leo in the folder as archived in 2019-09-21-Phantom-NewHeadline.zip:
```
Leo Log Window
Leo 6.1-devel, devel branch, build dc72b05e56
2019-09-28 22:28:17 +0200
Python 3.6.8, PyQt version 5.11.1
linux
import-jupyter-notebook requires nbformat package
setting leoID from os.getenv('USER'): 'bob'
current dir: /pri/bob/1/Leo
load dir: /pri/git/leo-editor/leo/core
global config dir: /pri/git/leo-editor/leo/config
home dir: /home/bob
reading settings in /pri/git/leo-editor/leo/config/leoSettings.leo
reading settings in /home/bob/.leo/myLeoSettings.leo
reading settings in /pri/git/leo_bug_demos/2019-09-21-Phantom-NewHeadline/atFileFailure01.leo
reading settings in /pri/git/leo_bug_demos/2019-09-21-Phantom-NewHeadline/atFileFailure01.leo
read 14 files in 0.01 seconds
read outline in 0.03 seconds
```

**Comment by maphew** [comment] 2019-09-30 06:20
A very different situation but similar in it's strangeness and involving @file, see #1359 - copy and rename wrongly wants to overwrite original. 

Your archive for me:
- code.leo: added a blank line to test07.py and saved: change was written to disk.
- atFileFailure01.leo: reads all nodes including test07.py, no errors reported in log:

~~~
Leo Log Window
Leo 6.1-devel, devel branch, build 2b8fc24bce
2019-09-29 06:30:27 -0500
Python 3.6.2, PyQt version 5.12.3
Windows 10 AMD64 (build 10.0.17134) SP0
current dir: C:/Users/mattw/Desktop/2019-09-21-Phantom-NewHeadline
load dir: C:/users/mattw/code/leo-editor/leo/core
global config dir: C:/users/mattw/code/leo-editor/leo/config
home dir: C:/Users/mattw
reading settings in C:/users/mattw/code/leo-editor/leo/config/leoSettings.leo
reading settings in C:/Users/mattw/.leo/myLeoSettings.leo
reading settings in C:/Users/mattw/Desktop/2019-09-21-Phantom-NewHeadline/atFileFailure01.leo
reading settings in C:/Users/mattw/Desktop/2019-09-21-Phantom-NewHeadline/atFileFailure01.leo
read 14 files in 0.03 seconds
read outline in 0.14 seconds
~~~

**Comment by vitalije** [comment] 2019-09-30 09:21
The problem is that inside atFileFailure01.leo gnx for test07.py is the same gnx that is located in the test06.py at root. At the start of reading test06.py, children nodes of test07.py are cleared.

**Comment by SegundoBob** [comment] 2019-09-30 15:53
[maphew](https://github.com/leo-editor/leo-editor/issues/1360#issuecomment-536418721),

Thanks.  If I understand you correctly, you were unable to reproduce my problem.

I intended for you to simply unzip and then open atFileFailure01.leo.  If at this point, the @file test07.py subtree is completely empty.  You will have reproduced the problem.

SegundoBob

**Comment by SegundoBob** [comment] 2019-09-30 16:01
[vitalije](https://github.com/leo-editor/leo-editor/issues/1360#issuecomment-536478730),

Wow.  Impressive debugging, surprising to me conclusion, but believable.

I'm 99% sure that I began test07.py by copying test07.py and then pasting it without retaining gnx's (i.e., Shift+Ctrl+V).   Similarly when I created xxx.py, I did Shift+Ctrl+V.  Yet in both cases, the GNX of the root node was retained.

I just tried to confirm this in a minimal file, but I can't get past:
```
The following were not written because of errors:

@file x.py

Warning: changes to these files will be lost
unless you can save the files successfully.
```
Yet no errors are shown in the Log pane and none are shown on the console.  This is another problem that should probably be fixed.

SegundoBob

**Comment by edreamleo** [comment] 2019-09-30 16:59
@SegundoBob The warning can't be "fixed".  It is a valid warning, and clear enough.

**Comment by edreamleo** [comment] 2019-09-30 17:03
If you should ever get really stuck, say at 3am in the morning, the workaround is to convert the @file node to @@file, then save.

**Comment by SegundoBob** [comment] 2019-09-30 17:44
Edward,

Do you mean the warning is valid in the sense that it truly indicates that the data will be lost if Leo-Editor is exited?  Yes, I verified with that.

But there is no hint about what the errors are and I have been unable to figure out what is wrong.

The issue is that Leo-Editor should either write the file or give some hint about what is wrong with the file.

Thanks for the suggested way to save my data.  But it doesn't write my file x.py.

Have you tried to reproduce the problem?  Create a new Leo-Editor file by opening it.  Change the root node headline to "@file x.py".  Try to save the new Leo-Editor file.

I have done this twice.  Both attempts failed.  Adding content to the x.py then does not get around the problem.

SegundoBob

**Comment by SegundoBob** [comment] 2019-09-30 17:54
Edward,

We should probably move this problem to a new "Warning with no explanation" issue.

You assigned this current issue to yourself, made it 6.1 and "first". 
Then when I explained that I tried to confirm an important point about this current issue, I ran into this "Warning with no explanation" problem.  This prompted you to close this current issue.  Was this close a mistake?

SegundoBob

**Comment by edreamleo** [comment] 2019-09-30 18:25
On Mon, Sep 30, 2019 at 12:44 PM SegundoBob <notifications@github.com>
wrote:

> But there is no hint about what the errors are and I have been unable to
> figure out what is wrong.


Usually this warning is given after an "error", which should be in the log.

Have you tried to reproduce the problem?


No.

> Create a new Leo-Editor file by opening it.


What does that mean?

Edward

**Comment by edreamleo** [comment] 2019-09-30 18:26
On Mon, Sep 30, 2019 at 12:54 PM SegundoBob <notifications@github.com>
wrote:

> We should probably move this problem to a new "Warning with no
> explanation" issue.
>
Yes, but first let's nail down how it happens.

Edward

**Comment by SegundoBob** [comment] 2019-09-30 18:52
Edward wrote:
>  Create a new Leo-Editor file by opening it.
> What does that mean?

I use a bash script leomy to run Leo-Editor.   Suppose I have a Bash shell and file test.leo does not exist in the shell's current working directory.  I create test.leo by opening it with the command line:
```
leomy test.leo
```
SegundoBob

**Comment by vitalije** [comment] 2019-09-30 20:27
@SegundoBob what are your revision? With the most recent I cannot reproduce your bug, but I have encountered this behaviour before and I think I have fixed it, at least on my computer it haven't happened since.

**Comment by edreamleo** [comment] 2019-09-30 20:59
On Mon, Sep 30, 2019 at 1:52 PM SegundoBob <notifications@github.com> wrote:

>
> I use a bash script leomy to run Leo-Editor. Suppose I have a Bash shell
> and file test.leo does not exist in the shell's current working directory.
> I create test.leo by opening it with the command line:
>
> leomy test.leo
>
>
This works for me.  Might there be permission issues?

Edward

**Comment by SegundoBob** [comment] 2019-09-30 21:27
[Vitalije](https://github.com/leo-editor/leo-editor/issues/1360#issuecomment-536737134),

The answer to your question is below in my answer to Edward.

[Edward](https://github.com/leo-editor/leo-editor/issues/1360#issuecomment-536749936),

Testing just now, I notice that the name of the external file matters.   Most names work fine.  The external file name x.py fails.
### Log Pane
```
2019-09-28 22:28:17 +0200
Python 3.6.8, PyQt version 5.11.1
linux
import-jupyter-notebook requires nbformat package
setting leoID from os.getenv('USER'): 'bob'
current dir: /pri/bob/1/Leo
load dir: /pri/git/leo-editor/leo/core
global config dir: /pri/git/leo-editor/leo/config
home dir: /home/bob
reading settings in /pri/git/leo-editor/leo/config/leoSettings.leo
reading settings in /home/bob/.leo/myLeoSettings.leo

wrote recent file: /home/bob/.leo/.leoRecentFiles.txt
not written: /sec/tmp/x.py
finished
 saved: test2.leo
```
### Additional symptom of a problem

The write fails.  So I exit and it asks if I want to save.  I say NO and the exit completes.  Since there is nothing in the external file and the "@file x.py" headline is saved in the .leo file, nothing is lost. Then when I reopen the Leo-Editor file, no errors are reported to the Log pane, but an error is reported to the console:
```
2019-09-30 14:20:37 /sec/tmp
$ leomy test2.leo

--global-docks: False

import-jupyter-notebook requires nbformat package
setting leoID from os.getenv('USER'): 'bob'
Leo 6.1-devel, devel branch, build dc72b05e56
2019-09-28 22:28:17 +0200
read_into_root Invalid external file: x.py
```
### Note
```
read_into_root Invalid external file: x.py
```

SegundoBob

**Comment by SegundoBob** [comment] 2019-09-30 21:45
Correction.  What is crucial is not the external file name, but that the external file already exist and that it is completely empty.  So before you begin the above instructions for reproducing it:
```
touch x.py
```

**Comment by vitalije** [comment] 2019-09-30 23:34
Well, Leo prevents you to overwrite file that was not read before. I guess until recently Leo would show the dialog asking for permision to overwrite file. Recently the code showing dialog was removed.

**Comment by edreamleo** [comment] 2019-10-01 07:38
On Mon, Sep 30, 2019 at 6:34 PM Виталије Милошевић <notifications@github.com>
wrote:

> Well, Leo prevents you to overwrite file that was not read before. I guess
> until recently Leo would show the dialog asking for permision to overwrite
> file. Recently the code showing dialog was removed.
>
I don't think I did that on purpose.

Edward

**Comment by edreamleo** [comment] 2019-10-01 08:12
My bad.  This is a recent serious bug at.precheck introduced at c5bd9953. The checkin is: Removed *weird* redundant, non-functional code in at.precheck.

This was a brain spike.  I thought the call to promptForDangerousWrite was the same as *should*PromptForDangersousWrite.

It's top priority to fix this bug.  It will be tricky, because I also want to fix #1347, which I had better reopen.

**Comment by edreamleo** [comment] 2019-10-01 08:22
I am going to close this issue.  I have just created #1361, which clarifies what happened.

**Closed by edreamleo** 2019-10-01 08:22 UTC
Labels: Bug, Duplicate

**Comment by SegundoBob** [comment] 2019-10-03 19:47
Test System
```
Leo 6.1-devel, devel branch, build 3dc83b4d61
2019-10-03 06:30:08 -0500
Python 3.6.8, PyQt version 5.11.1
linux
```
I verified that the above release fixes this problem.  That is, when an @file external Python (.py) file is added to a .leo file, and the .py file exists, the next Ctrl+S (save .leo file) pops up the warning question, file exists, overwrite?

SegundoBob

**Comment by edreamleo** [comment] 2019-10-03 22:50
@SegundoBob Thanks for the confirmation.
