### ISSUE TITLE
Using vim mode, Leo is not responsive in the body pane for while

### ISSUE THREAD

**Issue by benzolius** [leo-editor/leo-editor#293] opened 2016-07-06 08:01 UTC
I have a very small Leo file: 3 headlines and 1 body with 140 lines.
When navigating in the body (up, down, page-up, page-down), my cpu gets 100% usage and Leo becomes unresponsive.

In myLeoSettings.leo:

@bool enable-abbreviations = True
@bool vim-mode = True
@bool check_for_changed_external_files = True
@int qt-cursor-width = 3
@color body-sel-bg = black

Leo 5.4-devel, build 20160412153848, Tue Apr 12 15:38:48 CDT 2016
Git repo info: branch = master, commit = 250ad23c98c8
Python 3.4.3, PyQt version 5.2.1
linux
loadOnePlugin: can not load enabled plugin: leo.plugins.viewrendered

**Comment by edreamleo** [comment] 2016-07-06 13:46
Please copy the .leo file here so that I can investigate.

**Comment by benzolius** [comment] 2016-07-07 07:59
Thanks Edward,

Now I disabled:
@@bool check_for_changed_external_files = True

but doesn't solve the issue.

I can reproduce it on any file which contains a body with 140 lines, here is a test file:

`<?xml version="1.0" encoding="utf-8"?>

<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="zke.20160707104757.2" a="E"><vh>Logs</vh>
<v t="zke.20160707104819.1" a="E"><vh>Kern</vh>
<v t="zke.20160707104832.1"><vh>Current</vh></v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="zke.20160707104757.2"></t>
<t tx="zke.20160707104819.1"></t>
<t tx="zke.20160707104832.1">Jul  4 11:44:49 nightly kernel: [ 9121.679161] EXT4-fs (sdb4): mounted filesystem with ordered data mode. Opts: (null)
Jul  4 11:47:37 nightly kernel: [ 9289.087636] EXT4-fs (sda4): mounted filesystem with ordered data mode. Opts: (null)
Jul  4 13:00:47 nightly kernel: [13676.338446] usb 1-5: new high-speed USB device number 3 using ehci-pci
Jul  4 13:00:47 nightly kernel: [13676.479694] usb 1-5: New USB device found, idVendor=0951, idProduct=1653
Jul  4 13:00:47 nightly kernel: [13676.479702] usb 1-5: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Jul  4 13:00:47 nightly kernel: [13676.479708] usb 1-5: Product: DT 100 G2
Jul  4 13:00:47 nightly kernel: [13676.479711] usb 1-5: Manufacturer: Kingston
Jul  4 13:00:47 nightly kernel: [13676.479715] usb 1-5: SerialNumber: 001372982D2ABB21C5750020
Jul  4 13:00:47 nightly kernel: [13676.515990] usb-storage 1-5:1.0: USB Mass Storage device detected
Jul  4 13:00:47 nightly kernel: [13676.516107] scsi6 : usb-storage 1-5:1.0
Jul  4 13:00:47 nightly kernel: [13676.516193] usbcore: registered new interface driver usb-storage
Jul  4 13:00:48 nightly kernel: [13677.538573] scsi 6:0:0:0: Direct-Access     Kingston DT 100 G2        PMAP PQ: 0 ANSI: 0 CCS
Jul  4 13:00:48 nightly kernel: [13677.539276] sd 6:0:0:0: Attached scsi generic sg3 type 0
Jul  4 13:00:49 nightly kernel: [13678.400400] sd 6:0:0:0: [sdc] 62603264 512-byte logical blocks: (32.0 GB/29.8 GiB)
Jul  4 13:00:49 nightly kernel: [13678.402325] sd 6:0:0:0: [sdc] Write Protect is off
Jul  4 13:00:49 nightly kernel: [13678.402334] sd 6:0:0:0: [sdc] Mode Sense: 23 00 00 00
Jul  4 13:00:49 nightly kernel: [13678.404312] sd 6:0:0:0: [sdc] No Caching mode page found
Jul  4 13:00:49 nightly kernel: [13678.404321] sd 6:0:0:0: [sdc] Assuming drive cache: write through
Jul  4 13:00:49 nightly kernel: [13678.410451] sd 6:0:0:0: [sdc] No Caching mode page found
Jul  4 13:00:49 nightly kernel: [13678.410464] sd 6:0:0:0: [sdc] Assuming drive cache: write through
Jul  4 13:00:49 nightly kernel: [13678.427528]  sdc: sdc1
Jul  4 13:00:49 nightly kernel: [13678.433990] sd 6:0:0:0: [sdc] No Caching mode page found
Jul  4 13:00:49 nightly kernel: [13678.433999] sd 6:0:0:0: [sdc] Assuming drive cache: write through
Jul  4 13:00:49 nightly kernel: [13678.434004] sd 6:0:0:0: [sdc] Attached SCSI removable disk
Jul  4 13:00:57 nightly kernel: [13686.109946] FAT-fs (sdc1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
Jul  4 13:39:55 nightly kernel: [16022.124408] sdc: detected capacity change from 32052871168 to 0
Jul  4 13:40:11 nightly kernel: [16037.873065] usb 1-5: USB disconnect, device number 3
Jul  4 19:48:41 nightly kernel: [38131.189453] QXcbEventReader[9319]: segfault at 7f3fa16a6729 ip 00007f3fa16a6729 sp 00007f3f9ef1eea0 error 14
Jul  4 20:43:47 nightly kernel: [41434.351137] Peer 23.251.190.30:63291/59341 unexpectedly shrunk window 2479002899:2479010217 (repaired)
Jul  4 20:43:48 nightly kernel: [41435.126533] Peer 23.251.190.30:63291/59341 unexpectedly shrunk window 2479002899:2479010217 (repaired)
Jul  5 10:16:57 nightly kernel: [    0.000000] Initializing cgroup subsys cpuset
Jul  5 10:16:57 nightly kernel: [    0.000000] Initializing cgroup subsys cpu
Jul  5 10:16:57 nightly kernel: [    0.000000] Initializing cgroup subsys cpuacct
Jul  5 10:16:57 nightly kernel: [    0.000000] Linux version 3.13.0-91-generic (buildd@lgw01-21) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) ) #138-Ubuntu SMP Fri Jun 24 17:00:34 UTC 2016 (Ubuntu 3.13.0-91.138-generic 3.13.11-ckt39)
Jul  5 10:16:57 nightly kernel: [    0.000000] Command line: BOOT_IMAGE=/@/boot/vmlinuz-3.13.0-91-generic root=UUID=f75efdac-9b6b-4633-aae4-8c472b14429f ro rootflags=subvol=@ quiet splash vt.handoff=7
Jul  5 10:16:57 nightly kernel: [    0.000000] KERNEL supported cpus:
Jul  5 10:16:57 nightly kernel: [    0.000000]   Intel GenuineIntel
Jul  5 10:16:57 nightly kernel: [    0.000000]   AMD AuthenticAMD
Jul  5 10:16:57 nightly kernel: [    0.000000]   Centaur CentaurHauls
Jul  5 10:16:57 nightly kernel: [    0.000000] e820: BIOS-provided physical RAM map:
Jul  5 10:16:57 nightly kernel: [    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009fbff] usable
Jul  5 10:16:57 nightly kernel: [    0.000000] BIOS-e820: [mem 0x000000000009fc00-0x000000000009ffff] reserved
Jul  5 10:16:57 nightly kernel: [    0.000000] BIOS-e820: [mem 0x00000000000e0000-0x00000000000fffff] reserved
Jul  5 10:16:57 nightly kernel: [    0.000000] BIOS-e820: [mem 0x0000000000100000-0x00000000bea15fff] usable
Jul  5 10:16:57 nightly kernel: [    0.000000] BIOS-e820: [mem 0x00000000bea16000-0x00000000bea44fff] reserved
Jul  5 10:16:57 nightly kernel: [    0.000000] BIOS-e820: [mem 0x00000000bea45000-0x00000000bee3bfff] ACPI NVS
Jul  5 10:16:57 nightly kernel: [    0.000000] BIOS-e820: [mem 0x00000000bee3c000-0x00000000bf15dfff] reserved
Jul  5 10:16:57 nightly kernel: [    0.000000] BIOS-e820: [mem 0x00000000bf15e000-0x00000000bf15efff] usable
Jul  5 10:16:57 nightly kernel: [    0.000000] BIOS-e820: [mem 0x00000000bf15f000-0x00000000bf364fff] ACPI NVS
Jul  5 10:16:57 nightly kernel: [    0.000000] BIOS-e820: [mem 0x00000000bf365000-0x00000000bf7fffff] usable
Jul  5 10:16:57 nightly kernel: [    0.000000] BIOS-e820: [mem 0x00000000f8000000-0x00000000fbffffff] reserved
Jul  5 10:16:57 nightly kernel: [    0.000000] BIOS-e820: [mem 0x00000000fec00000-0x00000000fec00fff] reserved
Jul  5 10:16:57 nightly kernel: [    0.000000] BIOS-e820: [mem 0x00000000fec10000-0x00000000fec10fff] reserved
Jul  5 10:16:57 nightly kernel: [    0.000000] BIOS-e820: [mem 0x00000000fec20000-0x00000000fec20fff] reserved
Jul  5 10:16:57 nightly kernel: [    0.000000] BIOS-e820: [mem 0x00000000fed00000-0x00000000fed00fff] reserved
Jul  5 10:16:57 nightly kernel: [    0.000000] BIOS-e820: [mem 0x00000000fed61000-0x00000000fed70fff] reserved
Jul  5 10:16:57 nightly kernel: [    0.000000] BIOS-e820: [mem 0x00000000fed80000-0x00000000fed8ffff] reserved
Jul  5 10:16:57 nightly kernel: [    0.000000] BIOS-e820: [mem 0x00000000fef00000-0x00000000ffffffff] reserved
Jul  5 10:16:57 nightly kernel: [    0.000000] BIOS-e820: [mem 0x0000000100001000-0x000000023effffff] usable
Jul  5 10:16:57 nightly kernel: [    0.000000] NX (Execute Disable) protection: active
Jul  5 10:16:57 nightly kernel: [    0.000000] SMBIOS 2.7 present.
Jul  5 10:16:57 nightly kernel: [    0.000000] DMI: Gigabyte Technology Co., Ltd. To be filled by O.E.M./970A-DS3P, BIOS F1 04/08/2013
Jul  5 10:16:57 nightly kernel: [    0.000000] e820: update [mem 0x00000000-0x00000fff] usable ==&gt; reserved
Jul  5 10:16:57 nightly kernel: [    0.000000] e820: remove [mem 0x000a0000-0x000fffff] usable
Jul  5 10:16:57 nightly kernel: [    0.000000] No AGP bridge found
Jul  5 10:16:57 nightly kernel: [    0.000000] e820: last_pfn = 0x23f000 max_arch_pfn = 0x400000000
Jul  5 10:16:57 nightly kernel: [    0.000000] MTRR default type: uncachable
Jul  5 10:16:57 nightly kernel: [    0.000000] MTRR fixed ranges enabled:
Jul  5 10:16:57 nightly kernel: [    0.000000]   00000-9FFFF write-back
Jul  5 10:16:57 nightly kernel: [    0.000000]   A0000-BFFFF write-through
Jul  5 10:16:57 nightly kernel: [    0.000000]   C0000-CFFFF write-protect
Jul  5 10:16:57 nightly kernel: [    0.000000]   D0000-EBFFF uncachable
Jul  5 10:16:57 nightly kernel: [    0.000000]   EC000-FFFFF write-protect
Jul  5 10:16:57 nightly kernel: [    0.000000] MTRR variable ranges enabled:
Jul  5 10:16:57 nightly kernel: [    0.000000]   0 base 000000000000 mask FFFF80000000 write-back
Jul  5 10:16:57 nightly kernel: [    0.000000]   1 base 000080000000 mask FFFFC0000000 write-back
Jul  5 10:16:57 nightly kernel: [    0.000000]   2 base 0000BF800000 mask FFFFFF800000 uncachable
Jul  5 10:16:57 nightly kernel: [    0.000000]   3 disabled
Jul  5 10:16:57 nightly kernel: [    0.000000]   4 disabled
Jul  5 10:16:57 nightly kernel: [    0.000000]   5 disabled
Jul  5 10:16:57 nightly kernel: [    0.000000]   6 disabled
Jul  5 10:16:57 nightly kernel: [    0.000000]   7 disabled
Jul  5 10:16:57 nightly kernel: [    0.000000] TOM2: 000000023f000000 aka 9200M
Jul  5 10:16:57 nightly kernel: [    0.000000] x86 PAT enabled: cpu 0, old 0x7040600070406, new 0x7010600070106
Jul  5 10:16:57 nightly kernel: [    0.000000] original variable MTRRs
Jul  5 10:16:57 nightly kernel: [    0.000000] reg 0, base: 0GB, range: 2GB, type WB
Jul  5 10:16:57 nightly kernel: [    0.000000] reg 1, base: 2GB, range: 1GB, type WB
Jul  5 10:16:57 nightly kernel: [    0.000000] reg 2, base: 3064MB, range: 8MB, type UC
Jul  5 10:16:57 nightly kernel: [    0.000000] total RAM covered: 3064M
Jul  5 10:16:57 nightly kernel: [    0.000000] Found optimal setting for mtrr clean up
Jul  5 10:16:57 nightly kernel: [    0.000000]  gran_size: 64K 	chunk_size: 16M 	num_reg: 3  	lose cover RAM: 0G
Jul  5 10:16:57 nightly kernel: [    0.000000] New variable MTRRs
Jul  5 10:16:57 nightly kernel: [    0.000000] reg 0, base: 0GB, range: 2GB, type WB
Jul  5 10:16:57 nightly kernel: [    0.000000] reg 1, base: 2GB, range: 1GB, type WB
Jul  5 10:16:57 nightly kernel: [    0.000000] reg 2, base: 3064MB, range: 8MB, type UC
Jul  5 10:16:57 nightly kernel: [    0.000000] e820: update [mem 0xbf800000-0xffffffff] usable ==&gt; reserved
Jul  5 10:16:57 nightly kernel: [    0.000000] e820: last_pfn = 0xbf800 max_arch_pfn = 0x400000000
Jul  5 10:16:57 nightly kernel: [    0.000000] found SMP MP-table at [mem 0x000fd7a0-0x000fd7af] mapped at [ffff8800000fd7a0]
Jul  5 10:16:57 nightly kernel: [    0.000000] Scanning 1 areas for low memory corruption
Jul  5 10:16:57 nightly kernel: [    0.000000] Base memory trampoline at [ffff880000099000] 99000 size 24576
Jul  5 10:16:57 nightly kernel: [    0.000000] Using GB pages for direct mapping
Jul  5 10:16:57 nightly kernel: [    0.000000] init_memory_mapping: [mem 0x00000000-0x000fffff]
Jul  5 10:16:57 nightly kernel: [    0.000000]  [mem 0x00000000-0x000fffff] page 4k
Jul  5 10:16:57 nightly kernel: [    0.000000] BRK [0x01fe2000, 0x01fe2fff] PGTABLE
Jul  5 10:16:57 nightly kernel: [    0.000000] BRK [0x01fe3000, 0x01fe3fff] PGTABLE
Jul  5 10:16:57 nightly kernel: [    0.000000] BRK [0x01fe4000, 0x01fe4fff] PGTABLE
Jul  5 10:16:57 nightly kernel: [    0.000000] init_memory_mapping: [mem 0x23ee00000-0x23effffff]
Jul  5 10:16:57 nightly kernel: [    0.000000]  [mem 0x23ee00000-0x23effffff] page 2M
Jul  5 10:16:57 nightly kernel: [    0.000000] BRK [0x01fe5000, 0x01fe5fff] PGTABLE
Jul  5 10:16:57 nightly kernel: [    0.000000] init_memory_mapping: [mem 0x23c000000-0x23edfffff]
Jul  5 10:16:57 nightly kernel: [    0.000000]  [mem 0x23c000000-0x23edfffff] page 2M
Jul  5 10:16:57 nightly kernel: [    0.000000] init_memory_mapping: [mem 0x200000000-0x23bffffff]
Jul  5 10:16:57 nightly kernel: [    0.000000]  [mem 0x200000000-0x23bffffff] page 2M
Jul  5 10:16:57 nightly kernel: [    0.000000] init_memory_mapping: [mem 0x00100000-0xbea15fff]
Jul  5 10:16:57 nightly kernel: [    0.000000]  [mem 0x00100000-0x001fffff] page 4k
Jul  5 10:16:57 nightly kernel: [    0.000000]  [mem 0x00200000-0x3fffffff] page 2M
Jul  5 10:16:57 nightly kernel: [    0.000000]  [mem 0x40000000-0x7fffffff] page 1G
Jul  5 10:16:57 nightly kernel: [    0.000000]  [mem 0x80000000-0xbe9fffff] page 2M
Jul  5 10:16:57 nightly kernel: [    0.000000]  [mem 0xbea00000-0xbea15fff] page 4k
Jul  5 10:16:57 nightly kernel: [    0.000000] init_memory_mapping: [mem 0xbf15e000-0xbf15efff]
Jul  5 10:16:57 nightly kernel: [    0.000000]  [mem 0xbf15e000-0xbf15efff] page 4k
Jul  5 10:16:57 nightly kernel: [    0.000000] BRK [0x01fe6000, 0x01fe6fff] PGTABLE
Jul  5 10:16:57 nightly kernel: [    0.000000] init_memory_mapping: [mem 0xbf365000-0xbf7fffff]
Jul  5 10:16:57 nightly kernel: [    0.000000]  [mem 0xbf365000-0xbf3fffff] page 4k
Jul  5 10:16:57 nightly kernel: [    0.000000]  [mem 0xbf400000-0xbf7fffff] page 2M
Jul  5 10:16:57 nightly kernel: [    0.000000] BRK [0x01fe7000, 0x01fe7fff] PGTABLE
Jul  5 10:16:57 nightly kernel: [    0.000000] init_memory_mapping: [mem 0x100001000-0x1ffffffff]
Jul  5 10:16:57 nightly kernel: [    0.000000]  [mem 0x100001000-0x1001fffff] page 4k
Jul  5 10:16:57 nightly kernel: [    0.000000]  [mem 0x100200000-0x13fffffff] page 2M
Jul  5 10:16:57 nightly kernel: [    0.000000]  [mem 0x140000000-0x1ffffffff] page 1G
Jul  5 10:16:57 nightly kernel: [    0.000000] RAMDISK: [mem 0x34ab4000-0x36551fff]
Jul  5 10:16:57 nightly kernel: [    0.000000] ACPI: RSDP 00000000000f0490 000024 (v02 ALASKA)
Jul  5 10:16:57 nightly kernel: [    0.000000] ACPI: XSDT 00000000bee21070 000064 (v01 ALASKA    A M I 01072009 AMI  00010013)
Jul  5 10:16:57 nightly kernel: [    0.000000] ACPI: FACP 00000000bee26408 0000F4 (v04 ALASKA    A M I 01072009 AMI  00010013)
Jul  5 10:16:57 nightly kernel: [    0.000000] ACPI BIOS Warning (bug): Optional FADT field Pm2ControlBlock has zero address or length: 0x0000000000000000/0x1 (20131115/tbfadt-603)
Jul  5 10:16:57 nightly kernel: [    0.000000] ACPI: DSDT 00000000bee21170 005292 (v02 ALASKA    A M I 00000000 INTL 20051117)
Jul  5 10:16:57 nightly kernel: [    0.000000] ACPI: FACS 00000000bee36f80 000040
Jul  5 10:16:57 nightly kernel: [    0.000000] ACPI: APIC 00000000bee26500 00008E (v03 ALASKA    A M I 01072009 AMI  00010013)
Jul  5 10:16:57 nightly kernel: [    0.000000] ACPI: FPDT 00000000bee26590 000044 (v01 ALASKA    A M I 01072009 AMI  00010013)
Jul  5 10:16:57 nightly kernel: [    0.000000] ACPI: MCFG 00000000bee265d8 00003C (v01 ALASKA    A M I 01072009 MSFT 00010013)
</t>
</tnodes>
</leo_file>
`

**Comment by edreamleo** [comment] 2016-09-18 11:54
I don't see any problems on my machines, except possibly for delays caused by syntax coloring.

You might want to add @killcolor directives for large text.

I'll close this now.  Please reopen if @killcolor doesn't help.

**Closed by edreamleo** 2016-09-18 11:54 UTC
Labels: Bug
