### ISSUE TITLE
Erratic Scrolling Bug

### ISSUE THREAD

**Issue by ZoomQuiet** [leo-editor/leo-editor#265] opened 2016-04-19 22:29 UTC
## process

- when outline ahd many nodes levels
- body pane will display bottom ScrollArea for control left-right-slide
- so when i slide to right for show the deep nodes

![screenshot 2016-04-19 17 19 19](https://cloud.githubusercontent.com/assets/22494/14657353/0c662fae-0653-11e6-83f5-180db51895fd.png)

- but after any node action, such as jump into other node
- the body pane bottom ScrollArea always auto slide left, like:

![screenshot 2016-04-19 17 19 32](https://cloud.githubusercontent.com/assets/22494/14657357/1140834e-0653-11e6-9ec6-97b5a84135f0.png)

## question

- auto slide body pane is anti-use-wants
- make me can not see the deep nodes name
- how to setup make body pane keep my Scroll position?

## env

> Leo Log Window
> Leo 5.2-final, build 20160319041841, Sat Mar 19 04:18:41 CDT 2016
> Not running from a git repo
> Python 2.7.11, PyQt version 4.8.7
> darwin

**Comment by edreamleo** [comment] 2016-04-20 10:26
On Tue, Apr 19, 2016 at 5:29 PM, Zoom.Quiet <notifications@github.com>
wrote:

​> ​the body pane bottom ScrollArea always auto slide left.

Rev ​5235145​ removes a call to setHScroll(0) in qtree.scrollToItem. This
is likely the cause of the problem.  Please report how this works for you.

I noticed this call to setHScroll(0) recently while working on another
issue.  At that time, I wondered whether it was a good idea.

Edward

**Comment by ZoomQuiet** [comment] 2016-04-20 14:04
try the last version:

![screenshot 2016-04-20 09 01 25](https://cloud.githubusercontent.com/assets/22494/14677261/7e8cd294-06d6-11e6-914e-e893ab3a24c0.png)

- same 5.2 stable
- use hostkeys or mouse jump other node
- outline pane auto slide to left

BTW:
Rev ​5235145​  ingore setup 

myLeoSettings.leo#@settings-->Windows-->Splitter options-->@string initial_split_orientation = horizontal

the body pane always at bottom. config is not working

**Comment by edreamleo** [comment] 2016-04-20 16:30
> the body pane always at bottom. config is not working

Not this issue.

**Comment by ZoomQuiet** [comment] 2016-04-20 16:36
issue as [initial_split_orientation not work after Rev. ​5235145​ · Issue #267 · leo-editor/leo-editor](https://github.com/leo-editor/leo-editor/issues/267)

**Comment by JohnLunzer** [comment] 2016-04-21 13:05
Please see this [discussion](https://groups.google.com/forum/#!topic/leo-editor/Tlf4FVwDDSY) for a description of various situations which cause this issue.

**Comment by edreamleo** [comment] 2016-04-25 12:29
91dc594 restores previous code.  That is, qtree.scrollToItem is now as follows:
```
def scrollToItem(self, item):
    w = self.treeWidget
    hPos, vPos = self.getScroll()
    w.scrollToItem(item, w.EnsureVisible)
        # Fix #265: Erratic scrolling bug.
        # w.PositionAtCenter causes unwanted scrolling.
    self.setHScroll(0)
        # Necessary
```
It's not surprising that the w.PositionAtCenter hint caused the reported problems.

**Comment by JohnLunzer** [comment] 2016-04-25 19:17
This is indeed fixed in terms of scrolling, but there remains a slowdown when a chapter other than main is enabled. There is a visual artifact that accompanies this. It is difficult to notice and describe but the node selected before the navigation up or down blinks briefly before the next node is selected. I believe it is this "blink" that is slowing things down. 

For a comparison of speeds do a press and hold up or down when you are both within a chapter and within the main chapter. Do this on short non syntax color nodes so you don't also get the slowdown from syntax highlighting and body pane populating.

**Comment by edreamleo** [comment] 2016-04-26 14:51
On Mon, Apr 25, 2016 at 2:17 PM, John Lunzer <notifications@github.com>
wrote:

> This is indeed fixed in terms of scrolling, but there remains a slowdown
> when a chapter other than main is enabled. There is a visual artifact that
> accompanies this. It is difficult to notice and describe but the node
> selected before the navigation up or down blinks briefly before the next
> node is selected. I believe it is this "blink" that is slowing things down.
>
​This might be an unnecessary redraw. I'll look into it.

EKR

**Comment by JohnLunzer** [comment] 2016-04-26 18:47
Confirmed fixed. No slowdown when inside of a chapter.

**Comment by edreamleo** [comment] 2016-04-26 23:16
@JohnLunzer Thanks for the confirmation.

I am going to keep this open.  There is still one more @chapter bug: Alt-RtArrow in a Chapter can go "too far", resulting in no obvious selected node.  I'll fix this next.

**Comment by edreamleo** [comment] 2016-04-26 23:48
On Tue, Apr 26, 2016 at 1:47 PM, John Lunzer <notifications@github.com>
wrote:

> Confirmed fixed. No slowdown when inside of a chapter.
>
​Thanks for the confirmation.

EKR

**Comment by edreamleo** [comment] 2016-04-26 23:55
Rev abf1abb fixes the problem with Alt-Arrow, so I'll close this issue.

**Closed by edreamleo** 2016-04-26 23:55 UTC
Labels: Bug
