### ISSUE TITLE
Outline pane does not scroll horizontally with node headline edit

### ISSUE THREAD

**Issue by JohnLunzer** [leo-editor/leo-editor#176] opened 2015-04-02 11:58 UTC
I have some particularly long @clean filenames because they are on network drives. Currently if I begin editing the node and move my cursor to the right beyond where the text is displayed in the outline pane my cursor simply runs off the screen.

Because of this I am not able to operate in a keyboard only mode. Even with the expand pane shortcuts my node headlines are still longer than what can be displayed on my screen, so this is not a solution.

My suggestion is that the outline pane window automatically scrolls horizontally with the position of the edit cursor.

**Comment by JohnLunzer** [comment] 2015-04-02 12:11
I just found that there are commands for scrolling the outline right and left. 

While this offers a keyboard solution it is still not an intuitive one. First off the scroll-outline-right or scroll-outline-left shortcuts can not be used while the headline is in edit mode so this creates many extra keystrokes. 

Again, my suggestion is automatic scrolling.

**Comment by tbnorth** [comment] 2015-04-02 13:01
My work around for that issue has been:
```
@command edit-headline-long
    txt = g.app.gui.runAskOkCancelStringDialog(
        c, 'Edit headline', 'Edit headline', default=p.h)
    if txt and txt.strip():
        p.h = txt
```
which I bind to ``edit-headline-long = Ctrl-Alt-E``

which brings the headline up in a dialog that may also be too narrow (although it does scroll sideways automatically).  Depending on your window manager, a quick double click on the title bar of the dialog may expand it to full screen width, which is nice for editing very long headlines.

**Comment by JohnLunzer** [comment] 2015-04-02 13:57
This is a great little command and a sufficient workaround. Is there no way to programmatically control the size of these popup dialogues?

If nothing else changes this command should be added to Leo. That said, if more than one person is working around this then it might be worth trying to integrate a more natural solution.

**Comment by JohnLunzer** [comment] 2015-04-02 14:13
I went into qt_gui.py and added in d.resize(1300,100) to runAskOkCancelStringDialog. 

I recommend increasing this to at least 600 by default but moreover it should either auto adapt to the original string length or be a percentage of the screen size.

**Comment by tbnorth** [comment] 2015-04-02 14:23
On Thu, 02 Apr 2015 07:13:07 -0700
JohnLunzer <notifications@github.com> wrote:

> I went into qt_gui.py and added in d.resize(1300,100) to
> runAskOkCancelStringDialog. 

Probably needs some optional keyword arg. for
runAskOkCancelStringDialog() seeing it doesn't need to be wide when
asking for small pieces of text which it may more typically be doing.

Or maybe runAskOkCancelStringDialog could just maximize width when the
default text is more than n characters.  Hmm, don't know how easy that
is, given the interaction with the Windows manager required.

**Comment by JohnLunzer** [comment] 2015-04-02 14:44
The primary reason to use this function is if the text string is too long so the typical usage would see longer pieces of text. My default width of 600 was motivated by that fact that it's unlikely that anybody's screen will be smaller than 640 width. 

So this is my line now I added to runAskOkCancelStringDialog:
```
d.resize(int(g.windows()[0].get_window_info()[0]*.85),100)
```

This is not perfect but you could even by default change the multiplier to 50% or 60% of the window width and that would probably be fine for many. For me 85% works with my massive headlines.

**Comment by tbnorth** [comment] 2015-04-02 14:58
On Thu, 02 Apr 2015 07:44:07 -0700
JohnLunzer <notifications@github.com> wrote:

> The primary reason to use this function is if the text string is too
> long so the typical usage would see longer pieces of text. 

Not really, that's the primary use of the `edit-headline-long` command,
the primary use of runAskOkCancelStringDialog is to request pieces of
text from the user, they may be long or short.

But I think your approach is good - I didn't know about g.windows().

I'll put it in to the trunk.

Are you interested in commit privileges?  You seemed to work through
this issue effectively :-)

Cheers -Terry

**Comment by JohnLunzer** [comment] 2015-04-02 15:51
> Not really, that's the primary use of the `edit-headline-long` command,
> the primary use of runAskOkCancelStringDialog is to request pieces of
> text from the user, they may be long or short.

You are correct sir! I was getting the two confused, thinking runAskOkCancelStringDialog was specific to this case.

Thank you for the compliment, but I think commit privileges may be premature. I'll let you know when I'm ready ;)

**Comment by tbnorth** [comment] 2015-04-02 16:08
I pushed the wide text input in 6eee969 with a keyword arg. - it looked too odd for small texts to be on all the time.  So the workaround would be
```
@command edit-headline-long
    txt = g.app.gui.runAskOkCancelStringDialog(
        c, 'Edit headline', 'Edit headline', default=p.h,wide=True)
    if txt and txt.strip():
        p.h = txt
```
now (just adding `wide=True`).  But I don't really think this fixes this bug, it's still jarring to not be able to easily edit a long headline. The ideal would be to have the headline edit widget notice it was too short and open a lightweight textarea type widget in the same position as the line based input.

**Comment by edreamleo** [comment] 2015-04-02 22:45
Thanks, John and Terry, for this exchange.  I am going to close this now, in the interest in housekeeping.

In the future, I would appreciate that discussions of enhancements appear first on leo-editor, not here.  There is substantial administrative work involved in keeping track of issues, and I would like to reduce that if possible.

**Comment by tbnorth** [comment] 2015-04-04 14:21
This was a bug, not an enhancement, the extra flag on runAskOkCancelStringDialog was just to facilitate a workaround for the bug. I don't really think the workaround closes the bug, but given that fixing the bug properly might be quite difficult and the workaround helps a lot, I guess it can be closed. The `edit-headline-long` command above should really move in to core though.

**Comment by JohnLunzer** [comment] 2015-04-04 19:32
I would not consider this closed unless ```edit-headline-long``` was added to core as the functionality of editing long headline strings is difficult without it.

**Comment by edreamleo** [comment] 2015-04-05 11:23
I am going to reopen this bug as a reminder.  Closed bugs quickly slip into oblivion.

**Comment by edreamleo** [comment] 2015-04-05 11:23
On Sat, Apr 4, 2015 at 2:32 PM, John Lunzer <notifications@github.com>
wrote:

> I would not consider this closed unless edit-headline-long was added to
> core as the functionality of editing long headline strings is difficult
> without it.
>
​I've just reopened the bug as a reminder.

EKR

**Comment by JohnLunzer** [comment] 2015-08-11 12:14
Terry's recent declutter-tree feature with the rule:

# show the last part of long filenames
RULE ^.{1,1000}([/\\])(.{30})
REPLACE …\1\2

(the number 30 is at the discretion of the user)

Along with Edit-headline-long (with still needs to be integrated into the core) this helps immensely to address this issue.

**Comment by edreamleo** [comment] 2016-04-05 16:04
I am going to close this because it has the wontfix label.

**Comment by tbnorth** [comment] 2016-04-05 16:21
:-) you can't add a wontfix label with *absolutely no explanation* and then two days later use that label as a reason for closing :-)

Currently you can't edit long headlines in Leo. There are ways to avoid long headlines in some contexts, but this is a big wart, especially from a newbie perspective. edit-headline-long is not in core yet. If it was, I guess this could be demoted to wishlist, but currently it seems like a bug to me.

I.e. edit-headline-long helps, but the real issue is that the expected behavior would be scrolling when editing a long headline.  edit-headline-long doesn't have an obvious discovery path, whereas expected scrolling needs no discovery.

**Comment by edreamleo** [comment] 2016-04-05 16:33
I *can* edit arbitrarily long headlines on both windows 10 and ubuntu.  Hit Ctrl-h, then the end key. The text does show the ending text.  Furthermore, scrolling works for me on both platforms.

Would it help if I marked this invalid instead of wontfix?  I can leave this open, but I see nothing wrong with how Leo works.

EKR

**Comment by tbnorth** [comment] 2016-04-05 16:52
Aha, progress :-)  so it's a platform specific thing...

```
Leo 5.3-devel, build 20160405064755, Tue Apr  5 06:47:55 CDT 2016
Git repo info: branch = master, commit = d609e4a8a94e
Python 2.7.5, PyQt version 4.8.5
Windows 7 AMD64 (build 6.1.7601) SP1
```
Horizontal scrolling doesn't work for me, it scrolls half a char. when the cursor reaches the start or end of the line, but that's all, no way to see end of line. This is my work system, Python 3/Qt 5 is not an option.
```
Leo 5.3-devel, build 20160405103325, Tue Apr  5 10:33:25 CDT 2016
Git repo info: branch = master, commit = d0deb8803229
Python 2.7.6, PyQt version 4.8.6
linux2
```
Ubuntu 14.04 @ home - same problem.

I can't test Py3/Qt5 at the moment because Qt5 doesn't seem to work over VNC :-/ but will try at home.

@edreamleo don't know if you have any convenient Qt4 test environment?

**Comment by edreamleo** [comment] 2016-04-05 17:26
On Tue, Apr 5, 2016 at 11:52 AM, Terry Brown <notifications@github.com>
wrote:

> Aha, progress :-) so it's a platform specific thing...
>
> @edreamleo <https://github.com/edreamleo> don't know if you have any
> convenient Qt4 test environment?
>
​I have PyQt4 everywhere: on Ubuntu and Windows 10 with both Python 2 and
3.  I don't seem to have any PyQt5 test environment.

Perhaps this is a Windows 7 issue.

EKR

**Comment by tbnorth** [comment] 2016-04-05 17:39
On Tue, 05 Apr 2016 10:26:13 -0700
"Edward K. Ream" <notifications@github.com> wrote:

> ​I have PyQt4 everywhere: on Ubuntu and Windows 10 with both Python 2
> and 3.  I don't seem to have any PyQt5 test environment.
> 
> Perhaps this is a Windows 7 issue.

I see it in ubuntu as well, but maybe I need to try vanilla no plugin
test environment.

**Comment by technatica** [comment] 2016-04-05 17:49
Scrolling works for me on Linux Mint 17.2 KDE.

Leo 5.3-devel, build 20160404090438, Mon Apr  4 09:04:38 CDT 2016
Git repo info: branch = master, commit = ce01e9d81228
Python 2.7.6, PyQt version 4.8.6
linux2

Chris

**Comment by JohnLunzer** [comment] 2016-04-05 18:45
Edward, the behavior you're seeing is not being seen universally. I'm on windows7/Python2/qt4 and the behavior you describe after Ctrl+h then end key does not happen. I'm seeing the same thing as Terry describes. If you're not seeing it on Windows 10 then the only conclusion is that it is in fact a windows7 issue. 

I also think this bug should be labelled as lvl:medium because it has the potential to be a constant annoyance to those it does affect.

**Comment by edreamleo** [comment] 2016-04-05 20:03
On Tue, Apr 5, 2016 at 1:45 PM, John Lunzer <notifications@github.com>
wrote:

> I also think this bug should be labelled as lvl:medium because it has the
> potential to be a constant annoyance to those it does affect.
>
​How does labeling this bug help us to fix it?​ Perhaps it should be
labelled, "Can't Fix"...

EKR

**Comment by JohnLunzer** [comment] 2016-04-06 00:16
Mostly the lvl is for book-keeping. For the sake of anyone else that might encounter this issue and to prevent duplicates this issue should probably stay open, perhaps it should be labelled: "Don't know how to fix".

**Comment by tbnorth** [comment] 2016-04-06 03:54
I think the problem is the line
```
w.resizeColumnToContents(0) # 2009/12/22
```
at leo/core/LeoPy.leo#Code-->Qt gui-->@file ../plugins/qt_tree.py-->qtree.Drawing-->qtree.repaint

comment that out, and the problem goes away.  It does cause the display of ellipses at the edge of the tree.  If that's considered undesirable, an alternative is to call w.setColumnWidth(0, 0) just before editing.

commit 4719f3459c3ba35dd562c6c6662b4142b9833d13
Author: Edward K. Ream <edreamleo@gmail.com>
Date:   Tue Dec 22 06:14:21 2009 -0500

    A much better solution to the QTreeWidget scrollbar problem:
    Call w.resizeColumnToContents(0) in leoQtTree.repaint.
    Many Thanks to Vincent for this repair.

My guess is that the "QTreeWidget scrollbar problem" is that there isn't one, with that line commented out, not a horizontal one, anyway.
```
tw.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
```
doesn't help, because although the scroll bar appears, there's no handle to move, because the column width (from resizeColumnToContents()) is wider than the viewport.

Will experiment with leaving w.resizeColumnToContents(0) in but calling w.setColumnWidth(0, 0) just before editing.

**Closed** 2016-04-07 03:42 UTC
Labels: Bug, lvl:minor

**Comment by edreamleo** [comment] 2016-04-07 05:35
Thanks, Terry.  Looks like an elegant fix.
