### ISSUE TITLE
vr3-freeze flag lost after run vr3-update

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#4231] opened 2024-12-04 01:25 UTC
Leo Log Window
Leo 6.8.3-devel, devel branch, build 43bd49cdb6
2024-12-03 10:17:43 -0600
Python 3.12.0, PyQt version 6.5.3
darwin

Operate Step:

1. select a node
2. run vr3-freeze
3. the freeze flag is active
4. run vr3-update
5. the freeze flag is lost

The better result will be that the vr3-update does not affect vr3-freez command.

**Comment by tbpassin** [comment] 2024-12-04 03:21
I was of two minds about this but I think you are right and it would be better to change the behavior back.  I will think about it again (I need to reconstruct my reasoning) and probably submit a PR.

**Comment by wangzhaohe** [comment] 2024-12-24 02:23
It seems that `vr3.set_freeze()` takes no effect.

```python
@g.command('vr3-update')
def update_rendering_pane(event):
    """Update the rendering pane"""
    vr3 = getVr3(event)
    if not vr3: return

    c = event.get('c')
    old_freeze = vr3.freeze
    if old_freeze:
        vr3.set_unfreeze()
    vr3.update(tag='view', keywords={'c': c, 'force': True})
    if old_freeze:
        vr3.set_freeze()
```

**Comment by tbpassin** [comment] 2024-12-24 02:36
I was puzzled by that when I found out a few weeks ago. I will look into the rest of the code to try to sort it out.

**Comment by tbpassin** [comment] 2024-12-27 00:18
Fixed in PR https://github.com/leo-editor/leo-editor/pull/4254.

The root cause was that when I added the ability for the rendered view to scroll back to its previous scroll position after a reload, for some reason I made the code reset the freeze state.

**Comment by wangzhaohe** [comment] 2024-12-27 06:57
Thank you! Actually, I tried to find the reason, but I couldn't find it.

**Comment by tbpassin** [comment] 2024-12-27 13:44
It was hard to find! I found it by printing out g.callers() to see who was calling set_unfreeze().

**Comment by tbpassin** [comment] 2024-12-29 20:24
Closed as completed.

**Closed by tbpassin** 2024-12-29 20:24 UTC
Labels: Enhancement, Delegated
